---
- name: Ensure nginx directory exists
  ansible.builtin.file:
    path: "{{ base_directory }}/nginx"
    owner: "1000"
    state: "directory"
    mode: "0755"

- name: Add a templated config
  tags: nginx
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "{{ base_directory }}/nginx/{{ item.src }}"
    mode: "0644"
  with_items: "{{ nginx_configs }}"
  when: nginx_configs is defined
  notify: Restart nginx
