---
- name: Install authelia
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "authelia"
    service_image: "docker.io/authelia/authelia"
    image_tag: "latest"
    config_file: "configuration.yml"
    url: "{{ urls.authelia }}"
    # SECRETS
    smtp_host: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/smtp', env_slug='prod', secret_name='SMTP_HOST').value }}"
    smtp_user: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/smtp', env_slug='prod', secret_name='SMTP_USER').value }}"
    smtp_password: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/smtp', env_slug='prod', secret_name='SMTP_PASSWORD').value }}"
    smtp_sender: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/authelia', env_slug='prod', secret_name='AUTHELIA_SMTP_SENDER').value }}"
    jwt_secret: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/authelia', env_slug='prod', secret_name='AUTHELIA_JWT_SECRET').value }}"
    session_secret: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/authelia', env_slug='prod', secret_name='AUTHELIA_SESSION_SECRET').value }}"
    storage_encryption_key: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/authelia', env_slug='prod', secret_name='AUTHELIA_STORAGE_ENCRYPTION_KEY').value }}"
    hmac: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/authelia', env_slug='prod', secret_name='AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE').value }}"
    oidc_private: "{{ lookup('infisical.vault.read_secrets', project_id=infisical_project_id, path='/authelia', env_slug='prod', secret_name='AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE').value }}"
    # DEFAULTS
    secret_permissions: &secret_permissions
      owner: "4100"
      permission: "0600"
      destination_path: "{{ base_directory }}/{{ service_directory }}/secrets"

  roles:
    - role: urls
      tags: urls
    - role: config
      tags: config
      become: true
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}/data"
            owner: "4100"
          - path: "{{ base_directory }}/{{ service_directory }}/config"
          - path: "{{ base_directory }}/{{ service_directory }}/secrets"
        files:
          - destination_path: "{{ base_directory }}/{{ service_directory }}/config"
            owner: "4100"
            permission: "0600"
          - template_name: "AUTHELIA_JWT_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_SESSION_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_STORAGE_ENCRYPTION_KEY"
            <<: *secret_permissions
          - template_name: "AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY"
            <<: *secret_permissions
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 9091
        middlewares:
          - "internal-ip@file"
        additional_content: |2
            middlewares:
              authelia:
                forwardAuth:
                  address: "http://authelia:9091/api/verify?rd=https%3A%2F%2F{{ expanded_url }}%2F"
                  trustForwardHeader: true
                  authResponseHeaders: ["Remote-User","Remote-Groups","Remote-Name","Remote-Email"]
              authelia-basic:
                forwardAuth:
                  address: "http://authelia:9091/api/verify?auth=basic"
                  trustForwardHeader: true
                  authResponseHeaders: ["Remote-User","Remote-Groups","Remote-Name","Remote-Email"]
    - role: authelia_oidc
      tags: authelia
      vars:
        url: "{{ urls.portainer }}"
        service_name: "Portainer"
        redirect_uris:
          - https://{{ expanded_url }}
    - role: authelia_oidc
      tags: authelia
      vars:
        url: "{{ urls.miniflux }}"
        service_name: "Miniflux"
        redirect_uris:
          - https://{{ expanded_url }}/oauth2/oidc/callback
    - role: authelia_oidc
      tags: authelia
      vars:
        url: "{{ urls.immich }}"
        service_name: "Immich"
        redirect_uris:
          - https://{{ expanded_url }}/auth/login
          - https://{{ expanded_url }}/user-settings
          - https://{{ expanded_url }}/api/oauth/mobile-redirect
          - app.immich://
