---
- name: Install calibre-web
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "calibre-web"
    service_image: "linuxserver/calibre-web"
    image_tag: "latest"
    url: "{{ urls.calibre_web }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories: [{}]
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8083
        middlewares:
          - "authelia@file"
          - "internal-ip@file"
