---
- name: Install cloudflare-ddns
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "cloudflare-ddns"
    service_image: "favonia/cloudflare-ddns"
    image_tag: "latest"
    cf_token: "{{ lookup('infisical.vault.read_secrets', path='/cloudflare', env_slug='prod', secret_name='CF_API_TOKEN_DDNS').value }}"

  pre_tasks:
    - name: Get list of urls
      ansible.builtin.include_role:
        name: urls
      vars:
        url: "{{ item }}"
        accumulate: true
      loop: "{{ public|flatten(levels=1) }}"

    - name: Join urls
      ansible.builtin.set_fact:
        public_urls: "{{ all_urls | join(',') }}"
    - debug: var=public_urls

  roles:
    - role: config
      tags: config
    - role: docker
      tags: docker
