---
- name: Add a new service on control node
  gather_facts: false
  hosts: localhost
  connection: local
  vars_prompt:
    - name: service_directory
      prompt: Enter the service name
      private: false
  vars:
    add_docker: true

  tasks:
    - name: Set up folder
      ansible.builtin.file:
        path: "{{ base_directory }}/files/{{ service_directory }}/templates"
        owner: "1000"
        state: directory
        mode: "0755"
    - name: Create docker-compose.yml
      when: add_docker
      ansible.builtin.copy:
        mode: "0644"
        dest: "{{ base_directory }}/files/{{ service_directory }}/templates/\
          docker-compose.yml.j2"
        force: false
        content: |
          {% raw %}version: "{{ docker.compose_version }}"

          networks:
            {{ docker.traefik_network }}:
              external: true

          services:
            {{ service_directory }}:
              image: {{ image }}
              container_name: {{ service_directory }}
              restart: unless-stopped
              security_opt:
                - no-new-privileges
              networks:
                - {{ docker.traefik_network }}{% endraw %}
    - name: Create playbook
      ansible.builtin.copy:
        mode: "0644"
        dest: "{{ base_directory }}/playbooks/{{ service_directory }}.yml"
        force: false
        content: |
          ---
          - name: Install {{ service_directory }}
            hosts: homelab
            gather_facts: false
            vars:
              service_directory: "{{ service_directory }}"
              image: ""
              {% raw %}url: "{{ urls.{% endraw %}{{ service_directory }}{% raw %} }}"{% endraw %}

            {% raw %}
            roles:
              - role: urls
              - role: config
                vars:
                  config_directories:
                    - path: ""
                      owner: "1000"
                      permission: "0755"
              - role: docker
              - role: traefik
                vars:
                  traefik_servers:
                    - port: 8080
                  traefik_middlewares:
                    - "internal-ip@file"{% endraw %}
