---
- name: Create a user for certain services
  hosts: homelab
  gather_facts: false

  roles:
    - role: authelia
      tags: authelia
    - role: headscale
      tags: headscale
    - role: filebrowser
      tags: filebrowser
