---
- name: Install dozzle
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "dozzle"
    service_image: "amir20/dozzle"
    image_tag: "v6.2.3"
    network: "socket-net"
    url: "{{ urls.dozzle }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8080
        middlewares:
          - "authelia@file"
          - "internal-ip@file"
