---
- name: Install dozzle
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "dozzle"
    service_image: "amir20/dozzle"
    image_tag: "latest"
    network: "socket-net"
    url: "{{ urls.dozzle }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8080
        middlewares:
          - "authelia@file"
          - "internal-ip@file"
