---
- name: Generate API keys for various services
  hosts: homelab
  gather_facts: false

  tasks:
    - name: Generate for headscale
      tags: headscale
      community.docker.docker_container_exec:
        container: headscale
        chdir: /
        argv:
          - headscale
          - apikeys
          - create
          - "-o"
          - "json"
      register: headscale
    - name: Print API result
      ansible.builtin.debug:
        msg: ["HEADSCALE API GENERATED:", "{{ headscale.stdout | from_json }}"]
