---
- name: Install jellyfin
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "jellyfin"
    service_image: "jellyfin/jellyfin"
    image_tag: "latest"
    url: "{{ urls.jellyfin }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories:
          -
          - path: "{{ location.cache }}/{{ service_directory }}"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8096
        middlewares:
         - "internal-ip@file"
