---
- name: Install kener
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "kener"
    service_image: "docker.io/rajnandan1/kener"
    image_tag: "latest"
    url:

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 3000
        middlewares:
          - "internal-ip@file"
