---
- name: Install ladder
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "ladder"
    service_image: "ghcr.io/kubero-dev/ladder"
    image_tag: "latest"
    url: "{{ urls.ladder }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8080
        middlewares:
          - "internal-ip@file"
