---
- name: Install libReddit
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "libreddit"
    service_image: "libreddit/libreddit"
    image_tag: "latest"
    url: "{{ urls.libreddit }}"

  roles:
    - role: urls
    - role: config
      tags: config
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8080
        middlewares:
         - "internal-ip@file"
