---
- name: Install lidarr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "lidarr"
    service_image: "linuxserver/lidarr"
    image_tag: "latest"
    url: "{{ urls.lidarr }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8686
        middlewares:
          - "internal-ip@file"
