---
- name: Install mafl
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "mafl"
    service_image: "hywax/mafl"
    image_tag: "latest"
    url: "{{ urls.mafl }}"
    config_file: "config.yml"

  roles:
    - role: urls
    - role: config
      tags: config
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 3000
        middlewares:
          - "internal-ip@file"
