---
- name: Install moodist
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "moodist"
    service_image: "ghcr.io/remvze/moodist"
    image_tag: "latest"
    url: "{{ urls.moodist }}"

  roles:
    - role: urls
    - role: config
      tags: config
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8080
        middlewares:
          - "internal-ip@file"
