---
- name: Install morss
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "morss"
    service_image: "pictuga/morss"
    image_tag: "latest"
    url: "{{ urls.morss }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8000
        middlewares:
         - "internal-ip@file"
