---
- name: Install nginx-lemmy
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "nginx-lemmy"
    service_image: "nginx"
    image_tag: "mainline-alpine"
    config_file: "nginx.conf"

  roles:
    - role: config
    - role: nginx
      vars:
        nginx_config_override: "nginx_lemmy.conf"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        create_router: false
