---
- name: Install nicotine
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "nicotine"
    service_image: "sirjmann92/nicotineplus-proper"
    image_tag: "3.2.9"
    config_file: "config"
    url: "{{ urls.nicotine }}"
    user: "{{ lookup('infisical.vault.read_secrets', path='/soulseek', env_slug='prod', secret_name='SLSK_USERNAME').value }}"
    password: "{{ lookup('infisical.vault.read_secrets', path='/soulseek', env_slug='prod', secret_name='SLSK_PASSWORD').value }}"
    io_port: "{{ lookup('infisical.vault.read_secrets', path='/soulseek', env_slug='prod', secret_name='SLSK_PORT').value }}"
    bot_token: "{{ lookup('infisical.vault.read_secrets', path='/telegram', env_slug='prod', secret_name='DOWNLOAD_BOT_TOKEN').value }}"
    chat_id: "{{ lookup('infisical.vault.read_secrets', path='/telegram', env_slug='prod', secret_name='CHAT_ID').value }}"

  roles:
    - role: ufw
      vars:
        local: false
        port: 50300
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
          - path: "{{ base_directory }}/{{ service_directory }}/utils"
            owner: "1000"
            permission: "0755"
        files:
          - template_name: "{{ config_file }}"
            destination_path: "{{ base_directory }}/{{ service_directory }}"
            permission: "0644"
          - template_name: "finish.sh"
            destination_path: "{{ base_directory }}/{{ service_directory }}/utils"
            permission: "0655"
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        redirect: true
        servers:
          - port: 6565
        middlewares:
         - "internal-ip@file"
