---
- name: Install patrol
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "patrol"
    service_image: "ghcr.io/karimsa/patrol"
    image_tag: "latest"
    url: "{{ urls.patrol }}"
    config_file: "config.yml"

  pre_tasks:
    - name: Get list of services
      tags: urls
      ansible.builtin.set_fact:
        all_names: "{% if url.monitor is defined %}{{ all_names | default([]) + [item.key|capitalize]}}{% else %}{{ all_names | default([]) }}{% endif %}"
      vars:
        url: "{{ item.value }}"
      loop: "{{ urls | dict2items }}"
    - name: Get list of urls
      tags: urls
      ansible.builtin.include_role:
        name: urls
      vars:
        url: "{{ item.value }}"
        accumulate: true
        type: "monitor"
      loop: "{{ urls | dict2items }}"


  roles:
    - role: urls
    - role: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}/data"
            owner: "1000"
            permission: "0755"
          - path: "{{ location.docker_data }}/{{ service_directory }}/data/data.db"
            owner: "1000"
            state: "touch"
            permission: "0666"
        files:
          - template_name: "{{ config_file }}"
            destination_path: "{{ base_directory }}/{{ service_directory}}"
            permission: "0644"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8080
