---
- name: Add bookmarks to pgweb
  gather_facts: false
  hosts: homelab

  tasks:
    - name: Make pgweb bookmark files
      tags: config
      ansible.builtin.template:
        src: "{{ hostvars.localhost.base_directory }}/files/pgweb/templates/bookmark.toml"
        dest: "{{ base_directory }}/pgweb/bookmarks/{{ item }}.toml"
        mode: "0644"
      with_items: "{{ services }}"
      vars:
        postgres_url: "{{ lookup('infisical.vault.read_secrets', path='/'+item, env_slug='prod', secret_name=item|upper+'_POSTGRES_URL').value }}"
        services:
          - "miniflux"
          - "dendrite"
          - "sliding-sync"
          - "wa-bridge"
          - "lemmy"
          - "immich"
          - "piped"
