---
- name: Install picoshare
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "picoshare"
    service_image: "mtlynch/picoshare"
    image_tag: "latest"
    url: "{{ urls.picoshare }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
    - role: docker
      tags: docker
      vars:
        picoshare_secret: "{{ lookup('infisical.vault.read_secrets', path='/picoshare', env_slug='prod', secret_name='PS_SHARED_SECRET').value }}"
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 4001
