---
- name: Install prowlarr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "prowlarr"
    service_image: "linuxserver/prowlarr"
    image_tag: "latest"
    url: "{{ urls.prowlarr }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 9696
        middlewares:
         - "internal-ip@file"
