---
- name: Install radarr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "radarr"
    service_image: "linuxserver/radarr"
    image_tag: "latest"
    url: "{{ urls.radarr }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 7878
        middlewares:
         - "internal-ip@file"
