---
- name: Install searxng
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "searxng"
    service_image: "searxng/searxng"
    image_tag: "latest"
    config_file: "settings.yml"
    network: "redis-net"
    url: "{{ urls.searxng }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}_redis"
            owner: "999"
            permission: "0755"
        files:
          - template_name: "{{ config_file }}"
            destination_path: "{{ base_directory }}/{{ service_directory }}"
            permission: "0644"
        instance_name: "BIM SearXNG"
        searxng_secret: "{{ lookup('infisical.vault.read_secrets', path='/searxng', env_slug='prod', secret_name='SEARXNG_SECRET').value }}"
    - role: docker
      tags: docker
      attach_redis: true
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8080
        middlewares:
         - "internal-ip@file"
