- name: Setup homelab
  gather_facts: false
  hosts: homelab
  become: true

  tasks:
    - name: Make necessary directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner | default('1000') }}"
        state: directory
        mode: "0755"
      loop:
        - { path: "{{ base_directory }}" }
        - { path: "{{ location.films }}" }
        - { path: "{{ location.books }}" }
        - { path: "{{ location.music }}" }
        - { path: "{{ location.cache }}" }
        - { path: "{{ location.docker_data }}" }
        - { path: "{{ location.repos }}", owner: "1001" }

    - name: Install packages
      tags: packages
      ansible.builtin.include_role:
        name: packages
      vars:
        native:
          - curl
          - docker
          - python-requests
          - python-websocket-client
          - logrotate
          - ctop
          - cronie
        pip:
          - docker==6.1.3
          - docker-compose
          - pyyaml==5.3.1

    - name: User configuration
      tags: user
      block:
        - name: Make service users
          ansible.builtin.user:
            name: "{{ item.name }}"
            shell: /usr/sbin/nologin
            create_home: false
            uid: "{{ item.uid }}"
          loop:
            - name: "traefik"
              uid: 2000
            - name: "headscale"
              uid: 3010
            - name: "authelia"
              uid: 4100

        - name: Make git user
          ansible.builtin.user:
            name: "git"
            group: "git"
            groups: sshuser
            shell: /usr/bin/git-shell
            create_home: false
            uid: 1001

        - name: Add users to Docker group
          ansible.builtin.user:
            name: "{{ base_user }}"
            groups: docker
            append: true

    - name: Enable and start systemd services
      tags: systemd
      become: true
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
      loop:
        - "docker"
        - "logrotate.timer"
        - "cronie"
