---
- name: Install traefik-bouncer
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "traefik-bouncer"
    service_image: "fbonalair/traefik-crowdsec-bouncer"
    image_tag: "latest"

  roles:
    - role: config
      tags: config
    - role: docker
      tags: docker
