---
- name: Install traefik
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "traefik"
    service_image: "traefik"
    image_tag: "v2.10"
    config_file: "traefik.yml"
    network: "traefik-net"
    cf_email: "{{ lookup('infisical.vault.read_secrets', path='/cloudflare', env_slug='prod', secret_name='CF_EMAIL').value }}"
    cf_token: "{{ lookup('infisical.vault.read_secrets', path='/cloudflare', env_slug='prod', secret_name='CF_API_TOKEN_TRAEFIK').value }}"
    url: "{{ urls.traefik }}"

  pre_tasks:
    - name: Create docker network for traefik
      tags: docker
      community.docker.docker_network:
        name: "{{ docker.traefik_network }}"

    - name: Create docker network for traefik (exposed services)
      tags: docker
      community.docker.docker_network:
        name: "{{ docker.expose_network }}"

    - name: Check if logrotate is installed
      tags: packages
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "logrotate test result"
      debug:
        msg: "logrotate not installed. Run setup_remote.yml again"
      when: "'logrotate' not in ansible_facts.packages"

  roles:
    - role: ufw
      vars:
        local: false
        port: 80
    - role: ufw
      vars:
        local: false
        port: 443
    - role: urls
    - role: config
      become: true
      vars:
        directories:
          - path: "{{ base_directory }}/{{ service_directory }}/dynamic"
            owner: "1000"
            permission: "0755"
          - path: "{{ location.docker_data }}/{{ service_directory }}/certs"
            owner: "2001"
            permission: "0755"
          - path: "{{ location.docker_data }}/{{ service_directory }}/plugins/sources"
            owner: "2001"
            permission: "0755"
          - path: "/var/log/traefik"
            owner: "0"
            permission: "0755"
    - role: config
      tags: config
      vars:
        files:
          - template_name: "{{ config_file }}"
            destination_path: "{{ base_directory }}/{{ service_directory }}"
            permission: "0644"
        copies:
          - file_name: "middlewares.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/dynamic"
            permission: "0644"
          - file_name: "security.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/dynamic"
            permission: "0644"
    - role: docker
      tags: docker
      vars:
        run: false
    - role: traefik
      tags: traefik
      vars:
        create_service: false
        redirect: true
        service_name: "api@internal"
        trailing_slash: false
        router_name: "traefik"
        rule: "(Host(`{{ url.sub + '.' + base_tld }}`) && (PathPrefix(`/{{ url.path }}`) || PathPrefix(`/api`)))"
        middlewares:
          - "internal-ip@file"

  post_tasks:
    - name: Change owners of plugin directory
      become: true
      tags: permission
      ansible.builtin.shell: "sudo chown 2000:2000 \
                              {{ location.docker_data }}/{{ service_directory }}/\
                              plugins"

    - name: Restrict traefik certificates
      become: true
      tags: permission
      block:
        - name: Change owners
          ansible.builtin.shell: "sudo chown 2000:2000 \
                                  {{ location.docker_data }}/{{ service_directory }}/\
                                  certs/acme.json"
        - name: Change mode
          ansible.builtin.shell: "sudo chmod 600 \
                                  {{ location.docker_data }}/{{ service_directory }}/\
                                  certs/acme.json"
    - name: Restrict traefik logs
      become: true
      tags: permission
      block:
        - name: Change owners
          ansible.builtin.shell: "sudo chown 2000:2000 \
                                  /var/log/traefik/*.log"
        - name: Change mode
          ansible.builtin.shell: "sudo chmod 644 \
                                  /var/log/traefik/*.log"

    - name: Configure log rotate
      tags: log
      ansible.builtin.copy:
        mode: "0644"
        owner: "root"
        dest: "/etc/logrotate.d/traefik"
        force: false
        content: |
          /var/log/traefik/*.log {
            size 10M
            rotate 30
            missingok
            notifempty
            compress
            dateext
            dateformat .%Y-%m-%d
            create 0644 traefik traefik
            postrotate
              docker kill --signal="USR1" {{ service_directory }}
            endscript
          }
      become: true

    - name: Start compose file
      tags: ["docker", "deploy"]
      community.docker.docker_compose:
        project_src: "{{ base_directory }}/{{ service_directory }}"
        state: present
        pull: false
        remove_orphans: true
