---
- name: Install vaultwarden
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "vaultwarden"
    service_image: "vaultwarden/server"
    image_tag: "1.30.3"
    url: "{{ urls.vaultwarden }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
    - role: docker
      tags: docker
      vars:
        smtp_host: "{{ lookup('infisical.vault.read_secrets', path='/smtp', env_slug='prod', secret_name='SMTP_HOST').value }}"
        smtp_user: "{{ lookup('infisical.vault.read_secrets', path='/smtp', env_slug='prod', secret_name='SMTP_USER').value }}"
        smtp_sender: "{{ lookup('infisical.vault.read_secrets', path='/vaultwarden', env_slug='prod', secret_name='VAULTWARDEN_SMTP_SENDER').value }}"
        smtp_password: "{{ lookup('infisical.vault.read_secrets', path='/smtp', env_slug='prod', secret_name='SMTP_PASSWORD').value }}"
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 80
        middlewares:
         - "internal-ip@file"
