---
- name: Make user
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/usr/sbin/nologin') }}"
    create_home: "{{ item.home | default(false) }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
  with_items: "{{ create_host_users_users }}"
