---
- name: Install with pip
  tags: packages
  ansible.builtin.pip:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ packages_pip }}"
  when: packages_pip is defined
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"

- name: Install with native package manager
  tags: packages
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ packages_native }}"
  when: packages_native is defined
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
