---
- name: Install with pip
  tags: packages
  ansible.builtin.pip:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ pip }}"
  when: packages_pip is defined
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"
  become: true

- name: Install with native package manager
  tags: packages
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ native }}"
  when: packages_native is defined
  become: true
