---
- name: Run a temporary container and print output
  check_mode: false
  block:
    - name: Run a temporary container
      community.docker.docker_container:
        name: tmp
        detach: false
        output_logs: true
        cleanup: true
        entrypoint: "{{ entrypoint | default('') }}"
        image: "{{ image }}"
        mounts: "{{ mounts | default(omit) }}"
      register: result
    - name: Result of user creation
      ansible.builtin.debug:
        msg: "{{ result.container.Output }}"
      when: print_output
