---
- name: Run a temporary container and print output
  check_mode: false
  block:
    - name: Run a temporary container
      community.docker.docker_container:
        name: tmp
        detach: false
        output_logs: true
        cleanup: true
        entrypoint: "{{ run_temp_container_entrypoint | default('') }}"
        image: "{{ run_temp_container_image }}"
        mounts: "{{ run_temp_container_mounts | default(omit) }}"
      register: run_temp_container_result
    - name: Result of user creation
      ansible.builtin.debug:
        msg: "{{ run_temp_container_result.container.Output }}"
      when: print_output
