---
docker_attach_redis: false
docker_add_redis_volume: true
docker_attach_mariadb: false
docker_attach_postgres: false
docker_print_output: false

docker_state: "{{ state }}"
docker_recreate: true
docker_name: "{{ service_directory }}"
docker_image: "{{ image }}"
docker_restart_policy: unless-stopped
docker_networks:
  - name: "{{ docker.traefik_network }}"

docker_postgres_state: "{{ state }}"
docker_postgres_recreate: false
docker_postgres_alias: "{{ service_directory }}-postgres"
docker_postgres_volumes:
  - "{{ docker_postgres_location }}:/var/lib/postgresql/data"
