---
- name: Ensure existence of group "{{ base_user }}"
  ansible.builtin.group:
    name: "{{ base_user }}"
    state: present
    gid: "{{ base_group_id }}"

- name: Ensure group "sudo" exists
  ansible.builtin.group:
    name: sudo
    state: present

- name: Ensure group "sshuser" exists
  ansible.builtin.group:
    name: sshuser
    state: present

- name: Make base user {{ base_user }}
  ansible.builtin.user:
    name: "{{ base_user }}"
    group: "{{ base_user }}"
    groups: sudo,sshuser
    append: true
    shell: /bin/bash
    create_home: true
    password: "{{ setup_default_user_password | password_hash('sha512') }}"
    uid: "{{ base_user_id }}"

- name: Add authorized keys on this machine to {{ base_user }}
  ansible.posix.authorized_key:
    user: "{{ base_user }}"
    key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_ed25519.pub') }}"
