---
- name: Ensure destination path exists
  ansible.builtin.file:
    path: "{{ item.destination | dirname }}"
    state: directory
    mode: "0755"
  with_items: "{{ fetch_items_from_urls_urls }}"

- name: Fetch a file
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  with_items: "{{ fetch_items_from_urls_urls }}"
