---
- name: Template crontab scrip
  tags: cron
  ansible.builtin.template:
    src: "{{ hostvars.localhost.base_directory }}/files/{{ service_directory }}\
      /templates/{{ service_directory }}_cron.sh.j2"
    dest: "{{ base_directory }}/scripts/{{ service_directory }}_cron.sh"
    mode: "0555"
    owner: "1000"

- name: Make crontab for service backup
  tags: cron
  ansible.builtin.cron:
    name: "Backup {{ service_directory }}"
    weekday: "{{ backup_weekday }}"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    disabled: "{{ backup_cron_disabled }}"
    job: "{{ base_directory }}/scripts/{{ service_directory }}_cron.sh > /dev/null || \
      {{ base_directory }}/scripts/alert.sh \
      'ERROR: {{ service_directory }} backup failed!'"
