---
- name: Pull container repository
  tags: docker
  ansible.builtin.git:
    repo: "{{ docker_image_container_repository }}"
    dest: "{{ base_directory }}/containers"
    clone: true
    version: "{{ docker_image_container_branch }}"
    single_branch: true
    update: true

- name: Build {{ docker_image }}
  tags: docker
  community.docker.docker_image:
    name: "{{ docker_image }}"
    build:
      path: "{{ base_directory }}/containers/{{ docker_image | basename }}"
    force_source: "{{ docker_image_force }}"
    source: build
    state: "{{ docker_image_state }}"
    repository: "{{ docker_image_repository }}"
