version: "{{ docker.compose_version }}"

services:
  {{ service_directory }}:
    image: {{ service_image }}:{{ image_tag }}
    container_name: {{ service_directory }}
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    read_only: true
    environment:
      PUID: 1000
      CF_API_TOKEN: "{{ cf_token }}"
      DOMAINS: "{{ public_urls }}"
      EMOJI: "false"
      IP6_PROVIDER: "none"
