---
network: "traefik-net" # network to let traefik access bouncer
ipam_subnet: "" # first three digits of the subnet
config_file: "traefik.yml"

cf:
  email: ""
  token: ""
alpine:
  image: alpine:3.19.1
