---
network: dendrite-net
config_file: config.yaml
config_location: "{{ base_directory }}/{{ service_directory }}/config"
wab_shared_secret: ""
postgres:
  image: "postgres:15-alpine"
  user: ""
  password: ""
  db: "wabridge"
  location: "{{ location.docker_data }}/{{ service_directory }}/db"
  url:

appservice_registration:
  as_token: "{{ lookup('ansible.builtin.password', './tmp/as_token_file', chars=['ascii_letters', 'digits'], length=64) }}"
  hs_token: "{{ lookup('ansible.builtin.password', './tmp/hs_token_file', chars=['ascii_letters', 'digits'], length=64) }}"
  sender_localpart: "{{ lookup('ansible.builtin.password', './tmp/sender_localpart_file', chars=['ascii_letters', 'digits'], length=32) }}"
  destination: "{{ base_directory }}/dendrite/config/wa.yaml"
