---
- name: Create user and print result
  tags: ["headscale", "user"]
  block:
    - name: Create user
      community.docker.docker_container_exec:
        container: headscale
        chdir: /
        argv:
          - headscale
          - users
          - create
          - "{{ create_headscale_user_username }}"
          - "-o"
          - "json"
      register: user_result
      changed_when: (user_result.stdout | from_json)['error'] | length == 0
    - name: Result of user creation
      when: "(user_result.stdout | from_json)['error'] != 'rpc error: code = Unknown desc = user already exists'"
      ansible.builtin.debug:
        msg: "{{ (user_result.stdout | from_json) }}"
