---
- name: Create user and print result
  tags: ["headscale", "user"]
  check_mode: false
  block:
    - name: Create user
      community.docker.docker_container_exec:
        container: headscale
        chdir: /
        argv:
          - headscale
          - users
          - create
          - "{{ create_headscale_user_username }}"
      register: user_result
    - name: Result of user creation
      ansible.builtin.debug:
        msg: "{{ user_result.stdout }}"
