---
- name: Rule with only trusted IPs
  tags: ufw
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ ufw_port }}"
    proto: "{{ ufw_protocol }}"
    src: "{{ item }}"
    comment: "{{ ufw_comment | default(service_directory) }}"
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - "{{ base_tailnet }}/10"
    - 127.0.0.0/8
    - fd7a:115c:a1e0::/48
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  when: ufw_local
  notify: Reload firewall

- name: Rule with all IPs
  tags: ufw
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ ufw_port }}"
    protocol: "{{ ufw_protocol }}"
    comment: "{{ ufw_comment | default(service_directory) }}"
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  when: not ufw_local
  notify: Reload firewall
