---
- name: Rule applied to only trusted IPs
  tags: ufw
  community.general.ufw:
    rule: "{{ item.0.rule | default('allow') }}"
    port: "{{ item.0.port }}"
    proto: "{{ item.0.protocol | default('tcp') }}"
    src: "{{ item.1 }}"
    comment: "{{ item.0.comment | default(service_directory) }}"
  with_subelements:
    - "{{ ufw_rules }}"
    - src
    - skip_missing: true
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  when: item.0.local | default(true)
  notify: Reload firewall

- name: Rule applied to all IPs
  tags: ufw
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    protocol: "{{ item.protocol | default('tcp') }}"
    comment: "{{ item.comment | default(service_directory) }}"
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  loop: "{{ ufw_rules }}"
  when: not item.local
  notify: Reload firewall

- name: Enable ufw
  tags: ufw
  community.general.ufw:
    state: enabled
  become: true
