---
- name: Rule with only trusted IPs
  tags: ufw
  community.general.ufw:
    rule: "{{ rule | default('allow') }}"
    port: "{{ port }}"
    proto: "{{ protocol }}"
    src: "{{ item }}"
    comment: "{{ comment | default(service_directory) }}"
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - "{{ base_tailnet }}/10"
    - 127.0.0.0/8
    - fd7a:115c:a1e0::/48
  become: true
  when: local
  notify: Reload firewall

- name: Rule with all IPs
  tags: ufw
  community.general.ufw:
    rule: "{{ rule }}"
    port: "{{ port }}"
    protocol: "{{ protocol | default('tcp') }}"
    comment: "{{ comment | default(service_directory) }}"
  become: true
  when: not local
  notify: Reload firewall
