---
- name: Clone repo with specific branch
  tags: git
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ git_destination }}"
    clone: true
    version: "{{ git_branch }}"
    single_branch: true
    update: true
