---
- name: Make pgweb bookmark files
  tags: config
  ansible.builtin.template:
    src: "bookmark.toml.j2"
    dest: "{{ base_directory }}/pgweb/bookmarks/{{ item }}.toml"
    mode: "0644"
  with_items: "{{ pg.keys() | list }}"
  vars:
    # Use lookup plugin to programmatically fetch postgres url for each service
    postgres_url: "postgresql://{{ pg[item].user }}:{{ pg[item].password }}@{{ pg[item].host | default('postgres') }}/{{ pg[item].db }}?sslmode=disable"
