version: "{{ docker.compose_version }}"

networks:
  {{ docker.traefik_network }}:
    external: true

services:
  {{ service_directory }}:
    image: {{ service_image }}:{{ image_tag }}
    container_name: {{ service_directory }}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - {{ docker.traefik_network }}
