# TODO: MAKE SURE users.yml is there
- name: Run a temp container to generate the password hash
  ansible.builtin.include_role:
    name: docker
  vars:
    image: "authelia/authelia:4.37.5"
    entrypoint:
      - authelia
      - crypto
      - hash
      - generate
      - argon2
      - "--password"
      - "{{ password }}"
- name: Save password hash
  ansible.builtin.set_fact:
    hash: "{{ result.container.Output[8:-1] }}"
- name: Try and set admin to boolean
  block:
    - name: Set admin to boolean
      ansible.builtin.set_fact:
        admin: "{{ admin | bool }}"
- name: Append to users.yml
  become: true
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/authelia/config/users.yml"
    marker: "  # {mark} {{ username | upper }} CONFIGURATION"
    content: |2
        {{ username }}:
          disabled: false
          displayname: "{{ display_name }}"
          password: "{{ hash }}"
          email: {{ email }}
      {% if admin %}
          groups:
            - admin
      {% else %}
          groups: []
      {% endif %}
