---
- name: Make service directory
  tags: config
  ansible.builtin.file:
    path: "{{ base_directory }}/{{ service_directory }}"
    owner: "1000"
    state: directory
    mode: "0755"

- name: Make additional files/directories
  tags: config
  ansible.builtin.include_tasks: make_directories.yml
  when: config_directories is defined

- name: Template configuration files
  tags: ["config", "template"]
  ansible.builtin.include_tasks: template_files.yml
  when: config_files is defined

- name: Copy other files
  tags: config
  ansible.builtin.include_tasks: copy_files.yml
  when: config_copies is defined
