---
# TODO: MAKE SURE users.yml is there
- name: Run a temp container to generate the password hash
  ansible.builtin.include_role:
    name: run_temp_container
  vars:
    run_temp_container_image: "authelia/authelia:4.37.5"
    run_temp_container_entrypoint:
      - authelia
      - crypto
      - hash
      - generate
      - argon2
      - "--password"
      - "{{ create_authelia_user_password }}"
- name: Save password hash
  ansible.builtin.set_fact:
    hash: "{{ result.container.Output[8:-1] }}"
- name: Try and set admin to boolean
  block:
    - name: Set admin to boolean
      ansible.builtin.set_fact:
        admin: "{{ create_authelia_user_admin | bool }}"
- name: Append to users.yml
  become: true
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/authelia/config/users.yml"
    marker: "  # {mark} {{ create_authelia_user_username | upper }} CONFIGURATION"
    content: |2
        {{ create_authelia_user_username }}:
          disabled: false
          displayname: "{{ create_authelia_user_display_name }}"
          password: "{{ hash }}"
          email: {{ create_authelia_user_email }}
      {% if create_authelia_user_admin %}
          groups:
            - admin
      {% else %}
          groups: []
      {% endif %}
