---
- name: Set url
  tags: ["urls", "traefik", "homepage", "authelia", "oidc", "docker"]
  when: urls_url is not defined
  ansible.builtin.set_fact:
    urls_url: "{{ url }}"

- name: Parse URL
  tags: ["urls", "traefik", "homepage", "authelia", "oidc", "docker"]
  ansible.builtin.set_fact:
    expanded_url: "{%if urls_url != base_tld %}{{ urls_url.sub + '.' + base_tld }}\
      {% if urls_url.path is defined %}/{{ urls_url.path }}{% endif %}{% else %}{{ base_tld }}{% endif %}"

- name: Get accumulate paths
  tags: urls
  ansible.builtin.set_fact:
    iter: "{{ urls_url[urls_type] | default('false') }}"
  when: urls_accumulate

- name: Append urls
  tags: urls
  ansible.builtin.set_fact:
    all_urls: "{% if iter %}{{ all_urls | default([]) + [expanded_url] }}{% else %}{{ all_urls | default([]) }}{% endif %}"
  when: urls_accumulate
