---
- name: Parse URL
  tags: ["urls", "traefik", "homepage", "authelia", "oidc", "docker"]
  ansible.builtin.set_fact:
    expanded_url: "{%if urls_url != base_tld %}{{ urls_url.sub + '.' + base_tld }}\
      {% if urls_url.path is defined %}/{{ urls_url.path }}{% endif %}{% else %}{{ base_tld }}{% endif %}"

- name: Append urls
  tags: urls
  ansible.builtin.set_fact:
    all_urls: "{{ all_urls | default([]) + [expanded_url] }}{% else %}{{ all_urls | default([]) }}"
  when: urls_accumulate
