---
- name: Change default sysctl values
  tags: setup_systctl
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "/etc/sysctl.d/99-homelab.conf"
    state: present
  with_items:
    - name: net.ipv4.udp_rmem_min
      value: '8192'
    - name: net.ipv4.udp_wmem_min
      value: '8192'
    - name: net.ipv4.tcp_fastopen
      value: '3'
    - name: net.core.rmem_default
      value: '1048576'
    - name: net.core.rmem_max
      value: '7500000'
    - name: net.core.wmem_default
      value: '1048576'
    - name: net.core.wmem_max
      value: '7500000'
    - name: net.core.optmem_max
      value: '65536'
    - name: net.ipv4.tcp_rmem
      value: '4096 1048576 2097152'
    - name: net.ipv4.tcp_wmem
      value: '4096 65536 16777216'
    - name: net.ipv4.ip_forward
      value: '1'
