version: "{{ docker.compose_version }}"

networks:
  {{ docker.traefik_network }}:
    external: true

services:
  {{ service_directory }}:
    image: {{ service_image }}:{{ image_tag }}
    container_name: {{ service_directory }}
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      - {{ docker.traefik_network}}
    volumes:
      - ./error.html:/error
      - ./{{ config_file }}:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - {{ location.files }}/data/shared/dashboard:/homepage
