---
- name: Create docker network for communication with backend
  tags: ["network", "docker", "redis"]
  community.docker.docker_network:
    name: "{{ docker_redis_network }}"

- name: Add redis service
  tags: ["docker", "redis"]
  community.docker.docker_container:
    state: "{{ docker_redis_state }}"
    recreate: "{{ docker_redis_recreate }}"
    name: "{{ service_directory }}-redis"
    image: "{{ docker_redis_image }}"
    security_opts:
      - no-new-privileges
    restart_policy: "{{ docker_restart_policy }}"
    log_driver: json-file
    log_options:
      max-size: "50m"
      max-file: "4"
    networks:
      - name: "{{ docker_redis_network }}"
    read_only: true
    volumes: "{{ docker_redis_volumes | default(omit) }}"
    command: "{{ docker_redis_command | default(omit) }}"
    cap_drop:
      - ALL
    capabilities:
      - CHOWN
      - SETGID
      - SETUID

# {% if docker_attach_redis_volume %}
#     volumes:
#       - {{ location.docker_data }}/{{ service_directory }}_redis:/data
# {% endif %}
