---
- name: Add postgres service
  tags: ["docker", "postgres"]
  community.docker.docker_container:
    state: "{{ docker_postgres_state }}"
    recreate: "{{ docker_postgres_recreate }}"
    name: "{{ service_directory }}-postgres"
    image: "{{ docker_postgres_image }}"
    security_opts:
      - no-new-privileges
    restart_policy: "{{ docker_restart_policy }}"
    log_driver: json-file
    log_options:
      max-size: "50m"
      max-file: "4"
    networks:
      - name: "{{ docker_pgweb_network }}"
      - name: "{{ docker_postgres_network }}"
        aliases:
          - "{{ docker_postgres_alias }}"
    volumes: "{{ docker_postgres_volumes }}"
    command: "{{ docker_postgres_command | default(omit) }}"
    env:
      POSTGRES_USER: "{{ docker_postgres_user }}"
      POSTGRES_PASSWORD: "{{ docker_postgres_password }}"
      POSTGRES_DB: "{{ docker_postgres_db }}"
