---
- name: Add postgres service
  tags: ["docker", "postgres"]
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/{{ service_directory }}/docker-compose.yml"
    prepend_newline: true
    marker: "  # {mark} POSTGRES CONFIGURATION"
    content: |2
        {{ service_directory }}-postgres:
          image: {{ postgres.image }}
          container_name: {{ service_directory }}-postgres
          restart: unless-stopped
          security_opt:
            - no-new-privileges:true
          networks:
            pg-net:
              aliases:
                - {{ service_directory }}-postgres
            {{ network }}:
              aliases:
                - {{ postgres.alias | default(service_directory + '-postgres') }}
          volumes:
            - {{ postgres.location }}:/var/lib/postgresql/data
      {% if postgres_config is defined %}
            - ./{{ postgres_config }}:/etc/postgresql.conf
      {% endif %}
          environment:
              POSTGRES_USER: "{{ postgres.user }}"
              POSTGRES_PASSWORD: "{{ postgres.password }}"
              POSTGRES_DB: "{{ postgres.db }}"
