---
- name: Add postgres service
  tags: ["docker", "postgres"]
  community.docker.docker_container:
    state: "{{ docker_postgres_state }}"
    recreate: "{{ docker_postgres_recreate }}"
    name: "{{ service_directory }}-postgres"
    image: "{{ docker_postgres_image }}"
    security_opts:
      - no-new-privileges
    restart_policy: "{{ docker_restart_policy }}"
    log_driver: json-file
    log_options:
      max-size: "50m"
      max-file: "4"
    volumes: "{{ docker_postgres_volumes }}"
    command: "{{ docker_postgres_command | default(omit) }}"
    env:
      POSTGRES_USER: "{{ docker_postgres_user }}"
      POSTGRES_PASSWORD: "{{ docker_postgres_password }}"
      POSTGRES_DB: "{{ docker_postgres_db }}"

- name: Create docker network for communication with backend
  tags: ["network", "docker", "postgres"]
  community.docker.docker_network:
    name: "{{ docker_postgres_network }}"
    internal: true
    connected:
      - "{{ service_directory }}-postgres"
      - "{{ service_directory }}"
