---
- name: Add redis service
  tags: ["docker", "redis"]
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/{{ service_directory }}/docker-compose.yml"
    prepend_newline: true
    marker: "  # {mark} REDIS CONFIGURATION"
    content: |2
        {{ service_directory }}-redis:
          image: {{ redis.image }}
          container_name: {{ service_directory }}-redis
          restart: unless-stopped
          security_opt:
            - no-new-privileges:true
          logging: *default-logging
          networks:
            - {{ network }}
          read_only: true
      {% if add_redis_volume %}
          volumes:
            - {{ location.docker_data }}/{{ service_directory }}_redis:/data
      {% endif %}
          cap_drop:
            - ALL
          cap_add:
            - CHOWN
            - SETGID
            - SETUID
