---
- name: Add postgres service
  tags: ["docker", "postgres"]
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/{{ service_directory }}/docker-compose.yml"
    prepend_newline: true
    marker: "  # {mark} POSTGRES CONFIGURATION"
    content: |2
        {{ service_directory }}-postgres:
          image: postgres:{{ postgres_image_tag | default(docker.postgres_image_tag) }}
          container_name: {{ service_directory }}-postgres
          restart: unless-stopped
          security_opt:
            - no-new-privileges:true
          networks:
            pg-net:
              aliases:
                - {{ service_directory }}-postgres
            {{ network }}:
              aliases:
                - {{ postgres_alias | default(service_directory + '-postgres') }}
          volumes:
            - {{ postgres_location }}:/var/lib/postgresql/data
          environment:
              POSTGRES_USER: "{{ postgres_user }}"
              POSTGRES_PASSWORD: "{{ postgres_password }}"
              POSTGRES_DB: "{{ postgres_db }}"
