---
- name: Stop compose stack
  tags: ["docker", "deploy"]
  community.docker.docker_compose:
    project_src: "{{ base_directory }}/{{ service_directory }}"
    state: absent
    pull: false
    remove_orphans: true
  register: output

- name: Start compose stack
  tags: ["docker", "deploy"]
  community.docker.docker_compose:
    project_src: "{{ base_directory }}/{{ service_directory }}"
    state: present
    pull: false
    remove_orphans: true
  when: output.changed or docker_force_up
