---
- name: Deploy docker compose file
  tags: docker
  ansible.builtin.template:
    src: "{{ hostvars.localhost.base_directory }}/files/{{ service_directory }}/templates/docker-compose.yml.j2"
    dest: "{{ base_directory }}/{{ service_directory }}/docker-compose.yml"
    mode: "0644"
  when: service_directory is defined

- name: Add redis
  tags: ["docker", "redis"]
  ansible.builtin.include_tasks: add_redis.yml
  when: attach_redis

- name: Add postgres
  tags: ["docker", "postgres"]
  ansible.builtin.include_tasks: add_postgres.yml
  when: attach_postgres

- name: Start compose file
  tags: ["docker", "deploy"]
  community.docker.docker_compose:
    project_src: "{{ base_directory }}/{{ service_directory }}"
    state: present
    pull: false
    remove_orphans: true
  when: run and service_directory is defined

- name: Run temporary container
  ansible.builtin.include_tasks: run_temp_container.yml
  when: image is defined and service_directory is undefined and url is undefined
