---
- name: Install packages
  tags: packages
  ansible.builtin.include_role:
    name: packages
  vars:
    native:
      - docker
      - python-requests
      - python-websocket-client
      - ctop # (Optional) but useful for quick monitoring
    pip:
      - docker==6.1.3
      - docker-compose
      - pyyaml==5.3.1

- name: Enable and start systemd service
  tags: packages
  ansible.builtin.include_role:
    name: systemd
  vars:
    services:
      - "docker"

- name: Add users to Docker group
  ansible.builtin.user:
    name: "{{ base_user }}"
    groups: docker
    append: true
