---
- name: Make service config for Traefik
  tags: traefik
  ansible.builtin.template:
    src: "service.yml.j2"
    dest: "{{ base_directory }}/traefik/dynamic/{{ traefik_options.file_name }}.yml"
    mode: "0644"

- name: Add additional blocks
  tags: traefik
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/traefik/dynamic/{{ traefik_options.file_name }}.yml"
    marker: "  # {mark} ADDITIONAL CONFIGURATION"
    content: "{{ traefik_optins.additional_content }}"
  when: traefik_additional_content is defined

- name: Configure path redirect
  tags: traefik
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/traefik/dynamic/{{ traefik_options.file_name }}.yml"
    marker: "  #  {mark} PATH REDIRECT CONFIGURATION"
    content: |2
        middlewares:
          {{ service_directory }}-strip:
            stripprefix:
              prefixes: "/{{ url.path }}{{ '/' if traefik_options.trailing_slash == True}}"
          {{ service_directory }}-redirect:
            redirectregex:
              regex: "^(.*)/{{ url.path }}$"
              replacement: "$1/{{ url.path }}/"
  when: traefik_redirect
