---
- name: Make service config for Traefik
  tags: traefik
  ansible.builtin.template:
    src: "service.yml.j2"
    dest: "{{ base_directory }}/traefik/dynamic/{{ file_name | default(service_directory) }}.yml"

- name: Add additional blocks
  tags: traefik
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/traefik/dynamic/{{ file_name | default(service_directory) }}.yml"
    marker: "  # {mark} ADDITIONAL CONFIGURATION"
    content: "{{ additional_content }}"
  when: additional_content is defined

- name: Configure path redirect
  tags: traefik
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ base_directory }}/traefik/dynamic/{{ file_name | default(service_directory) }}.yml"
    marker: "  #  {mark} PATH REDIRECT CONFIGURATION"
    content: |2
        middlewares:
          {{ service_directory }}-strip:
            stripprefix:
              prefixes: "/{{ url.path }}{{ '/' if trailing_slash == True}}"
          {{ service_directory }}-redirect:
            redirectregex:
              regex: "^(.*)/{{ url.path }}$"
              replacement: "$1/{{ url.path }}/"
  when: redirect == True
