version: "{{ docker.compose_version }}"

networks:
  {{ docker.traefik_network }}:
    external: true

services:
  {{ service_directory }}:
    image: {{ service_image }}:{{ image_tag }}
    container_name: {{ service_directory }}
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      - {{ docker.traefik_network}}
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - {{ location.docker_data }}/{{ service_directory }}/data:/var/www/baikal/Specific:rw
      - ./{{ config_file }}:/var/www/baikal/config/baikal.yaml:rw
