---
- name: Add a new service on control node
  gather_facts: false
  hosts: localhost
  connection: local
  vars_prompt:
    - name: service_directory
      prompt: Enter the service name
      private: false
  vars:
    add_docker: true

  tasks:
    - name: Create variable file
      ansible.builtin.copy:
        mode: "0644"
        dest: "{{ base_directory }}/vars/{{ service_directory }}.yml"
        force: false
        content: |
          ---
          service_directory: "{{ service_directory }}"
          image: ""
          {% raw %}urls_url: "{{ urls.{% endraw %}{{ service_directory }}{% raw %} }}"{% endraw %}


          state: started

          traefik_middlewares:
            - "internal@file"
    - name: Create playbook
      ansible.builtin.copy:
        mode: "0644"
        dest: "{{ base_directory }}/playbooks/{{ service_directory }}.yml"
        force: false
        content: |
          ---
          - name: Install {{ service_directory }}
            hosts: homelab
            gather_facts: false
            vars_files:
              - vars/{{ service_directory }}.yml

            roles:
              - role: urls
              - role: docker
              - role: traefik
