---
- name: Fetch legit css
  tags: legit
  hosts: homelab
  vars:
    urls_url: "{{ urls.legit }}"

  roles:
    - role: urls
    - role: fetch_items_from_urls
      vars:
        fetch_items_from_urls_urls:
          - url: "https://{{ expanded_url }}/wardrobe/plain/jumper/legit/style.css"
            destination: "{{ base_directory }}/legit/style.css"
