---
- name: Fetch Lemmy css
  tags: lemmy
  hosts: homelab
  roles:
    - role: fetch_items_from_urls
      vars:
        fetch_items_from_urls_urls:
          - url: "https://git.bim.boats/wardrobe/plain/jumper/lemmy/_variables.whiskers_v8.scss"
            destination: "{{ base_directory }}/lemmy-ui/css/_variables.whiskers_v8.scss"
          - url: "https://git.bim.boats/wardrobe/plain/jumper/lemmy/whiskers_v8.scss"
            destination: "{{ base_directory }}/lemmy-ui/css/whisers_v8.scss"
          - url: "https://git.bim.boats/wardrobe/plain/jumper/lemmy/whiskers_v8.css"
            destination: "{{ base_directory }}/lemmy-ui/css/whiskers_v8.css"

- name: Fetch homepage css
  tags: homepage
  hosts: homelab
  roles:
    - role: fetch_items_from_urls
      vars:
        fetch_items_from_urls_urls:
          - url: "https://git.bim.boats/wardrobe/plain/jumper/homepage/custom.css"
            destination: "{{ base_directory }}/homepage/config/custom.css"

- name: Fetch cgit css
  tags: cgit
  hosts: homelab
  roles:
    - role: fetch_items_from_urls
      vars:
        fetch_items_from_urls_urls:
          - url: "https://git.bim.boats/wardrobe/plain/jumper/cgit/style.css"
            destination: "{{ base_directory }}/cgit/style.css"

- name: Fetch legit css
  tags: legit
  hosts: homelab
  roles:
    - role: fetch_items_from_urls
      vars:
        fetch_items_from_urls_urls:
          - url: "https://git.bim.boats/wardrobe/plain/jumper/legit/style.css"
            destination: "{{ base_directory }}/legit/style.css"
