---
- name: Generate a hosts file for the OpenWRT router
  hosts: bunny
  gather_facts: false
  vars:
    base_lanip: "{{ groupvars.homelab.base_lanip }}"
    base_tld: "{{ groupvars.homelab.base_tld }}"

  roles:
    - role: hosts_file
      vars:
        hosts_file_service_rules:
          - "{{base_lanip}} {{ base_tld }}"
