---
- name: Generate keys for various services
  hosts: homelab
  gather_facts: false

  tasks:
    - name: Generate API key for headscale
      when: service == "headscale_api"
      ansible.builtin.include_tasks: tasks/generate_headscale_api.yml

    - name: Generate PAK for headscale
      when: service == "headscale_pak"
      tags: headscale
      ansible.builtin.include_tasks: tasks/generate_headscale_pak.yml

    - name: Generate hash pair for Authelia OIDC
      tags: authelia
      ansible.builtin.include_tasks: tasks/generate_oidc_secret_hash_pair.yml
      when: service == "authelia"
