---
- name: Install packages
  tags: packages
  ansible.builtin.include_role:
    name: packages
  vars:
    packages_native:
      - cronie
      - curl
  when: ansible_distribution != "Debian"

- name: Install packages on Debian
  tags: packages
  ansible.builtin.include_role:
    name: packages
  vars:
    packages_native:
      - cron
      - curl
  when: ansible_distribution == "Debian"

- name: Setup script to notify when a cronjob fails
  ansible.builtin.template:
    src: "alert.sh.j2"
    dest: "{{ base_directory }}/scripts/alert.sh"
    mode: "0655"
  vars:
    bot_token: "{{ setup_cron_bot_token }}"
    chat_id: "{{ setup_cron_chat_id }}"

- name: Enable and start systemd service
  tags: packages
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_services:
      - "cronie"
  when: ansible_distribution != "Debian"

- name: Enable and start systemd service (Debian)
  tags: packages
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_services:
      - "cron"
  when: ansible_distribution == "Debian"
