---
- name: Install actual
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/actual.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: backup
