---
- name: Install actual
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "actual"
    image: "actualbudget/actual-server:24.2.0-alpine"
    url: "{{ urls.actual }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 5006
        middlewares:
          - "internal-ip@file"
    - role: cron
