---
- name: Install actual
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/actual.yml
  vars:
    service_directory: "actual"
    image: "actualbudget/actual-server:24.5.0-alpine"
    url: "{{ urls.actual }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 5006
        traefik_middlewares:
          - "internal-ip@file"
    - role: backup
    - role: homepage
