---
- name: Install adguard-home
  hosts: homelab:&proxy
  gather_facts: false
  vars_files:
    - vars/adguard-home.yml

  roles:
    - role: ufw
    - role: urls
    - role: files
      become: true
    - role: docker

- name: Configure traefik to route dashboard
  hosts: homelab:&traefik
  gather_facts: false
  vars_files:
    - vars/adguard-home.yml

  roles:
    - role: urls
    - role: traefik
