---
- name: Install anonymous-overflow
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/anonymous-overflow.yml

  roles:
    - role: urls
    - role: docker_image
    - role: docker
    - role: traefik
