---
- name: Install authelia
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/authelia.yml
  vars:
    service_directory: "authelia"
    image: "docker.io/authelia/authelia:4.38.8"
    url: "{{ urls.authelia }}"
    # DEFAULTS
    permissions: &permissions
      owner: "4100"
      permission: "0600"
    secret_permissions: &secret_permissions
      <<: *permissions
      destination_path: "{{ base_directory }}/{{ service_directory }}/secrets"

  pre_tasks:
    - name: Check for users configuration
      ansible.builtin.stat:
        path: "{{ base_directory }}/{{ service_directory }}/config/users.yml"
      register: config_results

  roles:
    - role: create_host_users
    - role: urls
    - role: files
      become: true
    - role: files
      when: not config_results.stat.exists
    - role: docker
    - role: traefik
    - role: authelia_oidc
    - role: authelia_oidc
    - role: authelia_oidc
    - role: backup
    - role: homepage
