---
- name: Install authelia
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/authelia.yml
  vars:
    service_directory: "authelia"
    image: "docker.io/authelia/authelia:4.38.7"
    url: "{{ urls.authelia }}"
    # DEFAULTS
    permissions: &permissions
      owner: "4100"
      permission: "0600"
    secret_permissions: &secret_permissions
      <<: *permissions
      destination_path: "{{ base_directory }}/{{ service_directory }}/secrets"

  pre_tasks:
    - name: Check for users configuration
      ansible.builtin.stat:
        path: "{{ base_directory }}/{{ service_directory }}/config/users.yml"
      register: config_results

  roles:
    - role: create_host_users
      vars:
        create_host_users_users:
          - name: "authelia"
            uid: 4100
    - role: urls
    - role: config
      become: true
      vars:
        config_directories:
          - path: "{{ base_directory }}/{{ service_directory }}/config"
          - path: "{{ base_directory }}/{{ service_directory }}/secrets"
          - path: "{{ location.docker_data }}/{{ service_directory }}/data"
            owner: "4100"
        config_files:
          - destination_path: "{{ base_directory }}/{{ service_directory }}/config"
            <<: *permissions
          - template_name: "AUTHELIA_JWT_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_SESSION_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_STORAGE_ENCRYPTION_KEY"
            <<: *secret_permissions
          - template_name: "AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET"
            <<: *secret_permissions
          - template_name: "AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY"
            <<: *secret_permissions
    - role: config
      when: not config_results.stat.exists
      vars:
        config_copy:
          - file_name: "users.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/config"
            <<: *permissions
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 9091
        traefik_middlewares:
          - "internal-ip@file"
        traefik_additional_content: |2
            middlewares:
              authelia:
                forwardAuth:
                  address: "http://authelia:9091/api/verify?rd=https%3A%2F%2F{{ expanded_url }}%2F"
                  trustForwardHeader: true
                  authResponseHeaders: ["Remote-User","Remote-Groups","Remote-Name","Remote-Email"]
              authelia-basic:
                forwardAuth:
                  address: "http://authelia:9091/api/verify?auth=basic"
                  trustForwardHeader: true
                  authResponseHeaders: ["Remote-User","Remote-Groups","Remote-Name","Remote-Email"]
    - role: authelia_oidc
      vars:
        authelia_oidc_url: "{{ urls.portainer }}"
        authelia_oidc_service_name: "Portainer"
        authelia_oidc_vars_file: "vars/portainer.yml"
    - role: authelia_oidc
      vars:
        authelia_oidc_url: "{{ urls.immich }}"
        authelia_oidc_service_name: "Immich"
        authelia_oidc_vars_file: "vars/immich.yml"
        authelia_oidc_redirect_uris:
    - role: authelia_oidc
      vars:
        authelia_oidc_url: "{{ urls.sftpgo }}"
        authelia_oidc_service_name: "Sftpgo"
        authelia_oidc_vars_file: "vars/sftpgo.yml"
    - role: backup
    - role: homepage
