---
- name: Install baikal
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/baikal.yml

  roles:
    - role: urls
    - role: files
      become: true
    - role: docker
    - role: traefik
    - role: backup
