---
- name: Install baikal
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/baikal.yml
  vars:
    service_directory: "baikal"
    image: "robinthrift/baikal:0.9.3-nginx"
    url: "{{ urls.baikal }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
        files:
          - permission: "0666"
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "internal-ip@file"
    - role: backup
