---
- name: Block IP ranges with UFW
  hosts: homelab
  gather_facts: false
  become: true

  pre_tasks:
    - name: Block IP ranges
      community.general.ufw:
        rule: deny
        src: "{{ item.src }}"
        comment: "{{ item.comment }}"
      loop:
        - src: "47.128.0.0/14"
          comment: "AWS"
      notify: Reload firewall
