---
- name: Install calibre-web
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/calibre-web.yml
  vars:
    service_directory: "calibre-web"
    image: "linuxserver/calibre-web:nightly"
    url: "{{ urls.calibre_web }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 8083
        traefik_middlewares:
          - "authelia@file"
          - "internal-ip@file"
        traefik_additional_content: |2
              calibre-web-opds:
                rule: "(Host(`{{ expanded_url }}`) && PathPrefix(`/opds`))"
                service: "{{ service_directory }}"
                tls: *modern
                middlewares:
                  - "internal-ip@file"
    - role: backup
    - role: homepage
