---
- name: Install calibre-web
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/calibre-web.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: backup
