---
- name: Gather cgit private repos
  tags: traefik
  hosts: homelab
  gather_facts: false

  tasks:
    - name: Get git url
      ansible.builtin.include_role:
        name: urls
      vars:
        - url: "{{ urls.cgit }}"

    - name: Get and format private repos
      set_fact:
        concat_rule:
          "(Host(`{{ expanded_url }}`) && ({% for item in private_repos %}PathPrefix\
           (`/{{ item }}`){{ ' || ' if not loop.last else '))' }}{% endfor %}"
