---
- name: Gather private routes
  import_playbook: cgit_private.yml

- name: Install cgit
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "cgit"
    service_image: "joseluisq/alpine-cgit"
    image_tag: "latest"
    config_file: "cgitrc"
    css_file: "style.css"
    url: "{{ urls.cgit }}"

  roles:
    - role: urls
    - role: config
      vars:
        files: [{}]
        copies:
          - file_name: "{{ css_file }}"
          - file_name: "about.html"
          - file_name: "header.html"
          - file_name: "syntax-highlighting.py"
            permission: "0655"
          - file_name: "favicon.ico"
        instance_name: "BIM Git Repositories"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        rule: "(Host(`{{ expanded_url }}`) && PathPrefix(`/`))"
        additional_content: |2
                priority: 1
              cgit-private-repos:
                rule: "{{ concat_rule }}"
                service: "{{ service_directory }}"
                priority: 10
                tls: *modern
                middlewares:
                  - "rewrite-cgit@file"
                  - "internal-ip@file"
              cgit-private:
                rule: "Host(`private-{{ expanded_url }}`)"
                service: "{{ service_directory }}"
                tls: *modern
                middlewares:
                  - "internal-ip@file"

            middlewares:
              rewrite-cgit:
                redirectRegex:
                  regex: "^https://{{ expanded_url }}/(.*)"
                  replacement: "https://private-{{ expanded_url }}/${1}"
