---
- name: Install cgit
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/cgit.yml

  pre_tasks:
    - name: Get full url
      tags: ["urls", "traefik", "homepage"]
      ansible.builtin.include_role:
        name: urls
    - name: Gather private routes
      ansible.builtin.include_tasks: ../tasks/get_private_repos.yml

  roles:
    - role: create_host_users
    - role: config
      when: cgit_options.css and (css_file | length > 0)
      vars:
        config_copies:
          - file_name: "{{ css_file }}"
    - role: config
      when: cgit_options.logo and (logo_file | length > 0)
      vars:
        config_copies:
          - file_name: "{{ logo_file }}"
    - role: config
      when: cgit_options.favicon and (favicon_file | length > 0)
      vars:
        config_copies:
          - file_name: "{{ favicon_file }}"
    - role: config
      when: cgit_options.about and (about_file | length > 0)
      vars:
        config_copies:
          - file_name: "{{ about_file }}"
    - role: config
      when: cgit_options.syntax_highlighting
      vars:
        config_copies:
          - file_name: "syntax-highlighting.py"
            permission: "0655"
    - role: docker
    - role: traefik
    - role: homepage
