---
- name: Install cgit
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/cgit.yml
  vars:
    service_directory: "cgit"
    image: "joseluisq/alpine-cgit:2.5"
    url: "{{ urls.cgit }}"

  pre_tasks:
    - name: Get full url
      ansible.builtin.include_role:
        name: urls
    - name: Gather private routes
      ansible.builtin.include_tasks: ../tasks/get_private_repos.yml

  roles:
    - role: create_host_users
      vars:
        create_host_users_users:
          - name: "git"
            uid: 1001
            group: "git"
            groups: "sshuser"
            shell: /usr/bin/git-shell
    - role: config
      when: css_file is defined
      vars:
        config_copies:
          - file_name: "{{ css_file }}"
    - role: config
      when: favicon_file is defined
      vars:
        config_copies:
          - file_name: "{{ favicon_file }}"
    - role: config
      when: about_file is defined
      vars:
        config_copies:
          - file_name: "{{ about_file }}"
    - role: config
      vars:
        config_files: [{}]
        config_copies:
          - file_name: "header.html"
          - file_name: "syntax-highlighting.py"
            permission: "0655"
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 80
        traefik_rule: "(Host(`{{ expanded_url }}`) && PathPrefix(`/`))"
        traefik_additional_content: |2
                priority: 1
              cgit-private-repos:
                rule: "{{ concat_rule }}"
                service: "{{ service_directory }}"
                priority: 10
                tls: *modern
                middlewares:
                  - "rewrite-cgit@file"
                  - "internal-ip@file"
              cgit-private:
                rule: "Host(`private-{{ expanded_url }}`)"
                service: "{{ service_directory }}"
                tls: *modern
                middlewares:
                  - "internal-ip@file"

            middlewares:
              rewrite-cgit:
                redirectRegex:
                  regex: "^https://{{ expanded_url }}/(.*)"
                  replacement: "https://private-{{ expanded_url }}/${1}"
