---
- name: Gather private routes
  import_playbook: cgit_private.yml

- name: Install cgit
  hosts: homelab
  gather_facts: false
  vars:
    - vars/cgit.yml
  vars:
    service_directory: "cgit"
    image: "joseluisq/alpine-cgit:2.5"
    url: "{{ urls.cgit }}"

  roles:
    - role: users
      vars:
        users:
          - name: "git"
            uid: 1001
            group: "git"
            groups: "sshuser"
            shell: /usr/bin/git-shell
    - role: urls
    - role: config
      when: css_file is defined
      vars:
        copies:
          - file_name: "{{ css_file }}"
    - role: config
      when: favicon_file is defined
      vars:
        copies:
          - file_name: "{{ favicon_file }}"
    - role: config
      when: about_file is defined
      vars:
        copies:
          - file_name: "{{ about_file }}"
    - role: config
      vars:
        files: [{}]
        copies:
          - file_name: "header.html"
          - file_name: "syntax-highlighting.py"
            permission: "0655"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        rule: "(Host(`{{ expanded_url }}`) && PathPrefix(`/`))"
        additional_content: |2
                priority: 1
              cgit-private-repos:
                rule: "{{ concat_rule }}"
                service: "{{ service_directory }}"
                priority: 10
                tls: *modern
                middlewares:
                  - "rewrite-cgit@file"
                  - "internal-ip@file"
              cgit-private:
                rule: "Host(`private-{{ expanded_url }}`)"
                service: "{{ service_directory }}"
                tls: *modern
                middlewares:
                  - "internal-ip@file"

            middlewares:
              rewrite-cgit:
                redirectRegex:
                  regex: "^https://{{ expanded_url }}/(.*)"
                  replacement: "https://private-{{ expanded_url }}/${1}"
