---
- name: Install cloudflare-ddns
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/cloudflare-ddns.yml
  vars:
    service_directory: "cloudflare-ddns"
    image: "favonia/cloudflare-ddns:1.11.0"

  pre_tasks:
    - name: Get list of urls
      tags: docker
      ansible.builtin.include_role:
        name: urls
      vars:
        urls_url: "{{ item.value }}"
        urls_accumulate: true
        urls_type: "public"
      loop: "{{ urls | dict2items }}"
    - name: Join urls
      tags: docker
      ansible.builtin.set_fact:
        public_urls: "{{ all_urls | join(',') }}"

  roles:
    - role: config
    - role: docker
