---
- name: Install cloudflare-ddns
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "cloudflare-ddns"
    image: "favonia/cloudflare-ddns:1.11.0"
    cf_token: "{{ lookup('get_secrets', path='/cloudflare', secret_name='CF_API_TOKEN_DDNS') }}"

  pre_tasks:
    - name: Get list of urls
      tags: urls
      ansible.builtin.include_role:
        name: urls
      vars:
        url: "{{ item.value }}"
        accumulate: true
        type: "public"
      loop: "{{ urls | dict2items }}"
    - name: Join urls
      ansible.builtin.set_fact:
        public_urls: "{{ all_urls | join(',') }}"
    - debug: var=public_urls

  roles:
    - role: config
      tags: config
    - role: docker
      tags: docker
