---
- name: Install dokemon
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "dokemon"
    image: "productiveops/dokemon:1.5.9"
    url: "{{ urls.dokemon }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 9090
        traefik_middlewares:
          - "internal-ip@file"
