---
- name: Install dozzle
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/dozzle.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik

  post_tasks:
    - name: Restart dozzle to pick up local socket
      tags: docker
      community.docker.docker_container:
        name: "{{ service_directory }}"
        state: started
        restart: true
        comparisons:
          "*": ignore
