---
- name: Install dozzle
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/dozzle.yml
  vars:
    service_directory: "dozzle"
    image: "amir20/dozzle:v6.2.5"
    url: "{{ urls.dozzle }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "authelia@file"
          - "internal-ip@file"
