---
- name: Install dozzle
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/dozzle.yml
  vars:
    service_directory: "dozzle"
    image: "amir20/dozzle:v6.2.7"
    url: "{{ urls.dozzle }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "authelia@file"
          - "internal-ip@file"
    - role: homepage
