---
- name: Install dweebui
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "dweebui"
    image: "lllllllillllllillll/dweebui:v0.40"
    url: "{{ urls.dweebui }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "internal-ip@file"
