---
- name: Install dweebui
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "dweebui"
    image: "lllllllillllllillll/dweebui:v0.20"
    url: "{{ urls.dweebui }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "internal-ip@file"
