---
- name: Install filestash
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/filestash.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: homepage
