---
- name: Install filebrowser
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/filebrowser.yml
  vars:
    service_directory: "filebrowser"
    image: "filebrowser/filebrowser:v2.27.0"
    url: "{{ urls.filebrowser }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories:
          -
          - path: "{{ location.docker_data }}/{{ service_directory }}/database.db"
            state: "touch"
            permission: "0666"
        config_files: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "authelia@file"
          - "internal-ip@file"
