---
- name: Install filestash
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "filestash"
    image: "machines/filestash:latest"
    url: "{{ urls.filestash }}"

  roles:
    - role: urls
    - role: config
      tags: config
      vars:
        directories: [{}]
    - role: docker
      tags: docker
    - role: traefik
      tags: traefik
      vars:
        servers:
          - port: 8334
        middlewares:
          - "internal-ip@file"
