---
- name: Install gonic
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "gonic"
    image: "sentriz/gonic:v0.16.2"
    url: "{{ urls.gonic }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}/playlists"
          - path: "{{ location.docker_data }}/{{ service_directory }}/podcasts"
          - path: "{{ location.docker_data }}/{{ service_directory }}/data"
          - path: "{{ location.cache }}/{{ service_directory }}"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 4747
        middlewares:
         - "internal-ip@file"
