---
- name: Install gonic
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/gonic.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: backup
    - role: homepage
