---
- name: Install headscale-panel
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "headscale-panel"
    image: "simcu/headscale-ui:0.1.4"
    url: "{{ urls['headscale-panel'] }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        middlewares:
         - "internal-ip@file"
