---
- name: Install headscale
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/headscale.yml
  vars:
    service_directory: "headscale"
    image: "headscale/headscale:v0.23.0-alpha5"
    url: "{{ urls.headscale }}"

  roles:
    - role: packages
      vars:
        packages_native:
          - tailscale
    - role: systemd
      vars:
        systemd_services:
          - tailscaled
    - role: create_host_users
      vars:
        create_host_users_users:
          - name: "headscale"
            uid: 3010
    - role: urls
    - role: config
      become: true
      vars:
        config_directories:
          - path: "{{ location.docker_data }}/{{ service_directory }}/socket"
            owner: "3010"
          - path: "{{ location.docker_data }}/{{ service_directory }}/data"
            owner: "3010"
        config_files:
          - owner: "3010"
            permission: "0640"
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "cors@file"
        traefik_additional_content: |2
            middlewares:
              cors:
                headers:
                  accessControlAllowMethods: ["GET", "OPTIONS", "PUT"]
                  accessControlAllowHeaders: "*"
                  accessControlAllowOriginListRegex: ["https?://(.*)\\.bim\\.boats"]
                  accessControlMaxAge: 100
                  addVaryHeader: "true"
    - role: backup

  post_tasks:
    - name: Create headscale user for node and join the tailnet
      tags: ["headscale", "tailscale", "user"]
      vars:
        username: "{{ base_hostname }}"
        login_server_url: "{{ expanded_url }}"
      block:
        - name: Create user
          ansible.builtin.include_role:
            name: create_headscale_user
        - name: Generate PAK for {{ base_hostname }}
          ansible.builtin.include_tasks: ../tasks/generate_headscale_pak.yml
        - name: Add to tailnet {{ base_hostname }}
          ansible.builtin.include_tasks: ../tasks/join_tailnet.yml
