---
- name: Install immich server
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/immich.yml

  roles:
    - role: urls
    - role: files
      become: true
    - role: docker # microservice
      vars:
        docker_name: "{{ service_directory }}-microservices"
        docker_command:
          - "start.sh"
          - "microservices"
    - role: docker # server
      vars:
        docker_name: "{{ service_directory }}-server"
        docker_command:
          - "start.sh"
          - "immich"
    - role: traefik
    - role: backup
