---
- name: Install jellyfin
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "jellyfin"
    image: "jellyfin/jellyfin:10.8.13"
    url: "{{ urls.jellyfin }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories:
          -
          - path: "{{ location.cache }}/{{ service_directory }}"
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 8096
        traefik_middlewares:
          - "internal-ip@file"
    - role: backup
