---
- name: Install kener
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "kener"
    image: "docker.io/rajnandan1/kener:latest"
    url: "{{ urls.kener }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 3000
        middlewares:
          - "internal-ip@file"
