---
- name: Install ladder
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "ladder"
    image: "ghcr.io/everywall/ladder:v0.0.21"
    url: "{{ urls.ladder }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "internal-ip@file"
