---
- name: Install ladder
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "ladder"
    image: "ghcr.io/kubero-dev/ladder:latest"
    url: "{{ urls.ladder }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "internal-ip@file"
