---
- name: Install lemmy
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/lemmy.yml
  vars:
    service_directory: "lemmy"
    image: "dessalines/lemmy:0.18.5"
    url: "{{ urls.lemmy }}"

  roles:
    - role: urls
    - role: config
      become: true
      vars:
        directories:
          -
          - path: "{{ postgres.location }}"
            owner: "70"
            permission: "0700"
          - path: "{{ location.docker_data }}/{{ service_directory }}/pictrs"
            owner: "991"
          - path: "{{ base_directory }}/{{ service_directory}}/css"
        files:
          -
          - template_name: "{{ postgres_config }}"
    - role: docker
      vars:
        attach_postgres: true
        run: false
    - role: traefik
      vars:
        servers:
          - port: 8536
        rule: "(Host(`{{ expanded_url }}`) && \
          {% raw %}((HeadersRegexp(`Accept`, `application\\\\/(?:activity|ld)\\\\+json`)){% endraw %} \
          || (Method(`POST`, `PUT`, `DELETE`, `PATCH`, `CONNECT`)) || (PathPrefix(`/api`) \
          || PathPrefix(`/pictrs`) || PathPrefix(`/feeds`) || PathPrefix(`/nodeinfo`) \
          || PathPrefix(`/.well-known`))))"
    - role: traefik
      file_name: "lemmy-ui"
      vars:
        service_name: "lemmy-ui"
        servers:
          - port: 8238
            url: "lemmy-ui"

  post_tasks:
    - name: Fetch lemmy css
      tags: css
      when: css_url is defined
      ansible.builtin.get_url:
        url: "{{ css_url }}/{{ item }}"
        dest: "{{ base_directory }}/{{ service_directory }}/css/{{ item }}"
        mode: "0644"
      loop:
        - "_variables.{{ css_name }}.scss"
        - "{{ css_name }}.css"
        - "{{ css_name }}.scss"

    - name: Start compose file
      tags: ["docker", "deploy"]
      ansible.builtin.include_role:
        name: docker
        tasks_from: down_and_up.yml
      vars:
        force_up: true
