---
- name: Install lemmy
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/lemmy.yml
  vars:
    service_directory: "lemmy"
    image: "dessalines/lemmy:0.19.3"
    url: "{{ urls.lemmy }}"

  roles:
    - role: urls
    - role: config
      become: true
      vars:
        config_directories:
          -
          - path: "{{ postgres.location }}"
            owner: "70"
            permission: "0700"
          - path: "{{ location.docker_data }}/{{ service_directory }}/pictrs"
            owner: "991"
        config_files:
          -
          - template_name: "{{ postgres_config }}"
    - role: docker
      vars:
        docker_attach_postgres: true
    - role: traefik
      vars:
        traefik_servers:
          - port: 8536
        traefik_rule: "(Host(`{{ expanded_url }}`) && \
          {% raw %}((HeadersRegexp(`Accept`, `application\\\\/(?:activity|ld)\\\\+json`)){% endraw %} \
          || (Method(`POST`, `PUT`, `DELETE`, `PATCH`, `CONNECT`)) || (PathPrefix(`/api`) \
          || PathPrefix(`/pictrs`) || PathPrefix(`/feeds`) || PathPrefix(`/nodeinfo`) \
          || PathPrefix(`/.well-known`))))"
    - role: traefik
      when: default_frontend
      vars:
        traefik_file_name: "lemmy-ui"
        traefik_service_name: "lemmy-ui"
        traefik_servers:
          - port: 8238
            url: "lemmy-ui"
    - role: homepage
    - role: backup
      vars:
        backup_minute: "30"
