---
- name: Install lemmy
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "lemmy"
    image: "dessalines/lemmy:0.18.5"
    lemmy_ui:
      image: "dessalines/lemmy-ui:0.18.5"
    postgres:
      image: "postgres:16-alpine"
    pictrs:
      image: "asonix/pictrs:0.4.5"
    url: "{{ urls.lemmy }}"
    network: "postgres-net"
    config_file: "config.hjson"
    # SECRETS
    postgres_user: "{{ lookup('get_secrets', path='/lemmy', secret_name='LEMMY_POSTGRES_USER') }}"
    postgres_password: "{{ lookup('get_secrets', path='/lemmy', secret_name='LEMMY_POSTGRES_PASSWORD') }}"
    smtp_sender: "{{ lookup('get_secrets', path='/lemmy', secret_name='LEMMY_SMTP_SENDER') }}"
    smtp_password: "{{ lookup('get_secrets', path='/lemmy', secret_name='LEMMY_SMTP_PASSWORD') }}"
    smtp_host: "{{ lookup('get_secrets', path='/smtp', secret_name='SMTP_HOST') }}"
    pictrs_api_key: "{{ lookup('get_secrets', path='/lemmy', secret_name='LEMMY_PICTRS_API_KEY') }}"
    postgres_db: "{{ service_directory}}"
    # DEFAULTS
    nginx_flavour: "nginx-lemmy"
    db_location: "{{ location.docker_data }}/{{ service_directory }}/db"

  roles:
    - role: urls
    - role: config
      become: true
      vars:
        directories:
          -
          - path: "{{ db_location }}"
            owner: "70"
            permission: "0700"
          - path: "{{ location.docker_data }}/{{ service_directory }}/pictrs"
            owner: "991"
          - path: "{{ base_directory }}/{{ service_directory}}/css"
        files: [{}]
    - role: docker
      vars:
        attach_postgres: true
        run: false
        postgres_location: "{{ db_location }}"
    - role: nginx
      vars:
        configs:
          - config_name: "lemmy"
            server_url: "{{ urls.lemmy.sub }}.{{ base_tld }}"
    - role: traefik
      vars:
        create_service: false
        service_name: "nginx-lemmy"

  post_tasks:
    - name: Fetch lemmy css
      tags: css
      ansible.builtin.get_url:
        url: https://codeberg.org/lckdscl/selfhosted_userstyles/raw/branch/master/jumper/lemmy/{{ item }}
        dest: "{{ base_directory }}/{{ service_directory }}/css/{{ item }}"
        mode: "0644"
      loop:
        - "_variables.whiskers_v8.scss"
        - "whiskers_v8.css"
        - "whiskers_v8.scss"

    - name: Start compose file
      tags: ["docker", "deploy"]
      ansible.builtin.include_tasks: roles/docker/tasks/down_and_up.yml
      vars:
        force_up: true
