---
- name: Install libReddit
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "libreddit"
    service_image: "libreddit/libreddit"
    image_tag: "latest"
    url: "{{ urls.libreddit }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
