---
- name: Install libReddit
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "libreddit"
    image: "libreddit/libreddit:latest"
    url: "{{ urls.libreddit }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
