---
- name: Install lidarr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "lidarr"
    image: "linuxserver/lidarr:latest"
    url: "{{ urls.lidarr }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8686
        middlewares:
          - "internal-ip@file"
