---
- name: Install mafl
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "mafl"
    image: "hywax/mafl:v0.9.2"
    url: "{{ urls.mafl }}"
    config_file: "config.yml"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 3000
        traefik_middlewares:
          - "internal-ip@file"
