---
- name: Install miniflux
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/miniflux.yml

  roles:
    - role: urls
    # - role: files
    #   become: true
    - role: docker
    # - role: traefik
    # - role: backup
 #   - role: authelia_oidc
