---
- name: Install miniflux
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/miniflux.yml
  vars:

  roles:
    - role: urls
    - role: config
      become: true
    - role: docker
      vars:
        docker_attach_postgres: true
    - role: traefik
    - role: homepage
    - role: backup
    - role: authelia_oidc
