---
- name: Install moodist
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "moodist"
    image: "ghcr.io/remvze/moodist:latest"
    url: "{{ urls.moodist }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
