---
- name: Install morss
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "morss"
    image: "pictuga/morss:latest"
    url: "{{ urls.morss }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "internal-ip@file"
