---
- name: Install mycorrhiza
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/mycorrhiza.yml

  roles:
    - role: urls
    - role: files
    - role: docker_image
    - role: docker
    - role: traefik
    - role: homepage
