---
- name: Install netbird dashboard
  hosts: vpn_host
  gather_facts: false
  vars_files:
    - vars/netbird-dash.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik

- name: Install netbird management server
  hosts: vpn_host
  gather_facts: false
  vars_files:
    - vars/netbird-mgmt.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: traefik
      vars:
        traefik_service_name: "nb-mgmt-grpc"
        traefik_router_name: "nb-mgmt-grpc"
        traefik_file_name: "nb-mgmt-grpc"
        traefik_protocol: "h2c"
        traefik_servers:
          - port: "443"
            url: "{{ docker_name }}"
        traefik_rule: "Host(`{{ expanded_url }}`) && PathPrefix(`/management.ManagementService/`)"

- name: Install netbird signal server
  hosts: vpn_host
  gather_facts: false
  vars_files:
    - vars/netbird-signal.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik

  post_tasks:
    - name: Setup netbird docker network
      community.docker.docker_network:
        name: "{{ service_directory }}-net"
        connected:
          - "{{ service_directory }}-dash"
          - "{{ service_directory }}-mgmt"
          - "{{ service_directory }}-signal"
          - "traefik"
        appends: true
        internal: false

- name: Install turn server for netbird
  hosts: vpn_host
  tags: turn
  gather_facts: false
  vars_files:
    - vars/coturn.yml

  roles:
    - role: urls
    - role: files
    - role: docker
