---
- name: Install nginx-private
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "nginx-private"
    image: "nginx:mainline-alpine3.18"
    config_file: "nginx.conf"

  roles:
    - role: config
    - role: nginx
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        create_router: false
