---
- name: Install nginx-lemmy
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "nginx-lemmy"
    image: "nginx:mainline-alpine3.18"
    config_file: "nginx.conf"

  roles:
    - role: config
    - role: setup_nginx
      vars:
        setup_nginx_config_override: "nginx_lemmy.conf"
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 80
        traefik_create_router: false
