---
- name: Install nginx
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "nginx"
    image: "nginx:mainline-alpine"
    config_file: "nginx.conf"

  roles:
    - role: config
    - role: nginx
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        create_router: false
