---
- name: Install nicotine
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/nicotine.yml
  vars:
    service_directory: "nicotine"
    image: "sirjmann92/nicotineplus-proper:3.2.9"
    url: "{{ urls.nicotine }}"

  roles:
    - role: ufw
      vars:
        local: false
        port: 50300
    - role: urls
    - role: config
      vars:
        directories:
          -
          - path: "{{ base_directory }}/{{ service_directory }}/utils"
        files:
          -
          - template_name: "finish.sh"
            destination_path: "{{ base_directory }}/{{ service_directory }}/utils"
            permission: "0655"
    - role: docker
    - role: traefik
      vars:
        redirect: true
        servers:
          - port: 6565
        middlewares:
         - "internal-ip@file"
