---
- name: Install opengists
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/opengist.yml
  vars:
    service_directory: "opengist"
    image: "ghcr.io/thomiceli/opengist:1"
    url: "{{ urls.opengists }}"

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
