---
- name: Install pgweb
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/pgweb.yml

  roles:
    - role: create_docker_network
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: create_pgweb_bookmarks
