---
- name: Install pgweb
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "pgweb"
    image: "sosedoff/pgweb:0.14.3"
    network: "pg-net"
    url: "{{ urls.pgweb }}"

  pre_tasks:
    - name: Create docker network for postgres databases
      tags: ["network", "docker"]
      community.docker.docker_network:
        name: "{{ docker.traefik_network }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories:
          - path: "{{ base_directory }}/{{ service_directory }}/bookmarks"
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 8081
        middlewares:
         - "internal-ip@file"

- name: Make bookmark links
  import_playbook: pgweb_bookmarks.yml
