---
- name: Install picoshare
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/picoshare.yml
  vars:
    service_directory: "picoshare"
    image: "mtlynch/picoshare:1.4.2"
    url: "{{ urls.picoshare }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 4001
