---
- name: Install piped backend
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/piped.yml

  roles:
    - role: urls
    - role: files
    - role: nginx
    - role: docker
    - role: traefik
    - role: backup

- name: Install piped proxy
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/piped-proxy.yml

  roles:
    - role: urls
    - role: files
    - role: nginx
    - role: docker
    - role: traefik

  post_tasks:
    - name: Check for actix socket
      tags: socket
      ansible.builtin.stat:
        path: "{{ socket_location }}/actix.sock"
      register: socket_results

    - name: Change permissions on actix.sock to 0777
      tags: ["socket", "permission"]
      become: true
      when: socket_results.stat.exists
      ansible.builtin.file:
        path: "{{ socket_location }}/actix.sock"
        mode: "0777"

- name: Install piped-frontend
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/piped-frontend.yml

  roles:
    - role: urls
    - role: files
    - role: nginx
    - role: docker
    - role: traefik
    - role: homepage
