---
- name: Install portainer
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/portainer.yml
  vars:
    service_directory: "portainer"
    image: "portainer/portainer-ee:2.20.2-alpine"
    url: "{{ urls.portainer }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_redirect: true
        traefik_trailing_slash: false
        traefik_servers:
          - port: 9000
        traefik_middlewares:
          - "internal-ip@file"
    - role: homepage
