---
- name: Install prowlarr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "prowlarr"
    image: "linuxserver/prowlarr:1.13.3"
    url: "{{ urls.prowlarr }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 9696
        middlewares:
         - "internal-ip@file"
