---
- name: Install prowlarr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "prowlarr"
    service_image: "linuxserver/prowlarr:latest"
    image_tag: "latest"
    url: "{{ urls.prowlarr }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 9696
        middlewares:
         - "internal-ip@file"

  post_tasks:
    - name: Create a container
      community.docker.docker_container:
        name: test
        image: traefik:v2.10
        capabilities:
          - sys_time
        cap_drop:
          - all
