---
- name: Install prowlarr
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/prowlarr.yml
  vars:
    service_directory: "prowlarr"
    image: "linuxserver/prowlarr:1.14.3"
    url: "{{ urls.prowlarr }}"

  roles:
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 9696
        traefik_middlewares:
          - "internal-ip@file"
    - role: homepage
