---
- name: Install qbittorrent
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/qbittorrent.yml
  vars:
    service_directory: "qbittorrent"
    image: "gists/qbittorrent:4.6.3"
    url: "{{ urls.qbittorrent }}"

  roles:
    - role: ufw
      vars: &ufw_defaults
        local: false
        port: 6881
    - role: ufw
      vars:
        <<: *ufw_defaults
        protocol: "udp"
    - role: urls
    - role: config
      vars:
        directories:
          - path: "{{ base_directory }}/{{ service_directory }}/utils/vuetorrent"
          - path: "{{ base_directory }}/{{ service_directory }}/config"
        files:
          - destination_path: "{{ base_directory }}/{{ service_directory }}/config"
          - template_name: "add.sh"
            destination_path: "{{ base_directory }}/{{ service_directory }}/utils"
          - template_name: "finish.sh"
            destination_path: "{{ base_directory }}/{{ service_directory }}/utils"
        copies:
          - file_name: "categories.json"
            destination_path: "{{ base_directory }}/{{ service_directory }}/config"
    - role: git
      vars:
        repo: https://github.com/VueTorrent/VueTorrent.git
        destination: "{{ base_directory }}/{{ service_directory }}/utils/vuetorrent"
        branch: latest-release
    - role: docker
    - role: traefik
      vars:
        redirect: true
        servers: [{}]
        middlewares:
         - "internal-ip@file"
