---
- name: Install qbittorrent
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/qbittorrent.yml

  roles:
    - role: ufw
    - role: urls
    - role: files
    - role: git
    - role: docker
    - role: traefik
    - role: homepage
