---
- name: Install readeck
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/readeck.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: backup
