---
- name: Install readeck
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/readeck.yml
  vars:
    service_directory: "readeck"
    image: "codeberg.org/readeck/readeck:0.12.0"
    url: "{{ urls.readeck }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "internal-ip@file"
    - role: cron
