---
- name: Install reiverr
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "reiverr"
    image: "ghcr.io/aleksilassila/reiverr:latest"
    url: "{{ urls.reiverr }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 9494
        middlewares:
          - "internal-ip@file"
