---
- name: Install reiverr
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/reiverr.yml

  roles:
    - role: urls
    - role: config
    - role: docker
    - role: traefik
    - role: homepage
