- name: Setup homelab
  gather_facts: true
  hosts: all
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  vars_prompt:
    - name: setup_default_user_password
      prompt: Enter the base user's password (not root user's password)

  pre_tasks:
    - name: Make necessary directories
      tags: dirs
      ansible.builtin.file:
        path: "{{ base_directory }}"
        owner: "{{ item.owner | default('1000') }}"
        state: directory
        mode: "0755"
    - name: Make additional directories
      tags: dirs
      ansible.builtin.file:
        path: "{{ item.value }}"
        owner: "{{ item.owner | default('1000') }}"
        state: directory
        mode: "0755"
      loop: "{{ location | dict2items }}"

  roles:
    - role: setup_python
    - role: setup_default_user
      tags: user
    - role: setup_sshd
      tags: sshd
    - role: setup_ufw
      tags: ufw
    - role: setup_docker
      tags: setup_docker
    - role: setup_cron
      tags: setup_cron
