- name: Setup control node
  gather_facts: true
  hosts: localhost
  connection: local

  tasks:
    # workaround to make playbooks in subdirectories work
    - name: Get variables
      ansible.builtin.include_vars:
        dir: ../host_vars

    - name: Create symbolic link for variables
      tags: config
      ansible.builtin.file:
        src: "{{ base_directory }}/{{ item }}"
        dest: "{{ base_directory }}/playbooks/{{ item }}"
        state: link
      loop:
        - host_vars
        - group_vars
        - vars
        - requirements.yml

    - name: Create symbolic link for variables
      tags: config
      ansible.builtin.file:
        src: "{{ base_directory }}/{{ item }}"
        dest: "{{ base_directory }}/tools/{{ item }}"
        state: link
      loop:
        - host_vars
        - group_vars
        - vars
        - requirements.yml

    - name: Install collections
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: "requirements.yml"

    - name: Generate keypair
      tags: ssh
      community.crypto.openssh_keypair:
        path: "/home/{{ lookup('env', 'USER') }}/.ssh/id_ed25519"
        type: "ed25519"
