- name: Setup homelab
  gather_facts: false
  hosts: homelab
  become: true

  pre_tasks:
    - name: Make necessary directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner | default('1000') }}"
        state: directory
        mode: "0755"
      loop:
        - { path: "{{ base_directory }}/scripts" }
        - { path: "{{ base_directory }}" }
        - { path: "{{ location.films }}" }
        - { path: "{{ location.books }}" }
        - { path: "{{ location.music }}" }
        - { path: "{{ location.cache }}" }
        - { path: "{{ location.docker_data }}" }
        - { path: "{{ location.repos }}", owner: "1001" }
    - name: Make git user
      ansible.builtin.user:
        name: "git"
        group: "git"
        groups: sshuser
        shell: /usr/bin/git-shell
        create_home: true
        uid: 1001
    - name: Install packages
      tags: packages
      ansible.builtin.include_role:
        name: packages
      vars:
        packages_native:
          - ufw
    - name: Enable and start systemd services
      tags: systemd
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - "ufw"

  roles:
    - role: setup_docker
    - role: setup_cron
