---
- name: Install sftpgo
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "sftpgo"
    image: "drakkan/sftpgo:2.5.x-alpine"
    url: "{{ urls.sftpgo }}"

  roles:
    - role: ufw
      vars:
        port: 2022
    - role: urls
    - role: config
      vars:
        directories:
          -
          - path: "{{ location.files }}"
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "internal-ip@file"
    - role: traefik
      vars:
        file_name: "webdav"
        service_name: "webdav"
        rule: "Host(`{{ urls.webdav }}.{{ base_tld }}`)"
        servers:
          - port: 10080
            url: "sftpgo"
        middlewares:
          - "internal-ip@file"
