---
- name: Install sftpgo
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/sftpgo.yml
  vars:
    service_directory: "sftpgo"
    image: "drakkan/sftpgo:edge-alpine"
    url: "{{ urls.sftpgo }}"

  roles:
    - role: ufw
      vars:
        ufw_port: 2022
    - role: urls
    - role: config
      vars:
        config_directories:
          -
          - path: "{{ location.files }}"
        config_copies:
          - file_name: "files.html"
    - role: docker
    - role: traefik
      vars:
        traefik_servers: [{}]
        traefik_middlewares:
          - "internal-ip@file"
    - role: traefik
      vars:
        traefik_file_name: "webdav"
        traefik_service_name: "webdav"
        traefik_rule: "Host(`{{ urls.webdav.sub }}.{{ base_tld }}`)"
        traefik_servers:
          - port: 10080
            url: "sftpgo"
        traefik_middlewares:
          - "internal-ip@file"
    - role: homepage
