---
- name: Install sftpgo
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/sftpgo.yml
  vars:
    service_directory: "sftpgo"
    image: "drakkan/sftpgo:edge-alpine"
    url: "{{ urls.sftpgo }}"

  roles:
    - role: ufw
      vars:
        port: 2022
    - role: urls
    - role: config
      vars:
        directories:
          -
          - path: "{{ location.files }}"
        copies:
          - file_name: "files.html"
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
        middlewares:
          - "internal-ip@file"
    - role: traefik
      vars:
        file_name: "webdav"
        service_name: "webdav"
        rule: "Host(`{{ urls.webdav.sub }}.{{ base_tld }}`)"
        servers:
          - port: 10080
            url: "sftpgo"
        middlewares:
          - "internal-ip@file"
