---
- name: Install socket-proxy-dozzle
  hosts: homelab:!dozzle
  gather_facts: false
  vars_files:
    - vars/socket-proxy-dozzle.yml

  roles:
    - role: docker

- name: Install socket-proxy-isaiah
  hosts: homelab:!dozzle
  gather_facts: false
  vars_files:
    - vars/socket-proxy-isaiah.yml

  roles:
    - role: docker
