---
- name: Deploy static sites
  hosts: homelab
  gather_facts: false
  vars:
    static_path: "{{ location.files }}/data/shared/static"
    nginx_defaults: &nginx_defaults
      config_src: "site"
    dashboard: &dashboard
      - nginx_config_name: "homepage"
        <<: *nginx_defaults
        nginx_server_url: "{{ base_tld }}"

  handlers:
    - name: Restart compose stack
      ansible.builtin.import_tasks: ../roles/docker/handlers/main.yml

  roles:
    - role: nginx
      vars:
        nginx_flavour: "nginx"
        nginx_configs:
          - *dashboard
          - config_name: "status"
            <<: *nginx_defaults
            server_url: "{{ urls.tinystatus.sub }}.{{ base_tld }}"
        nginx_mounts:
          - reference: "status page"
            host_location: "{{ static_path }}/status"
            container_location: "/status"
          - reference: "homepage"
            host_location: "{{ static_path }}/dashboard_public"
            container_location: "/homepage"
    - role: nginx
      vars:
        nginx_flavour: "nginx-private"
        nginx_configs:
          - *dashboard
        nginx_mounts:
          - reference: "homepage"
            host_location: "{{ static_path }}/dashboard"
            container_location: "/homepage"
    - role: traefik
      vars:
        traefik_file_name: "dashboard"
        traefik_service_name: "nginx-private"
        traefik_create_service: false
        traefik_router_name: "private-dashboard"
        traefik_rule: "Host(`{{ base_tld }}`)"
        traefik_middlewares:
          - "public-dashboard@file"
          - "internal-ip@file"
        traefik_additional_content: |2
            middlewares:
              public-dashboard:
                errors:
                  status: 403
                  service: "nginx"
                  query: "/index.html"
    - role: traefik
      vars:
        traefik_file_name: "status"
        traefik_service_name: "nginx"
        traefik_create_service: false
        traefik_router_name: "status"
        traefik_rule: "Host(`{{ urls.tinystatus.sub }}.{{ base_tld }}`)"
