---
- name: Install statping
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/statping.yml
  vars:
    service_directory: "statping"
    image: "adamboutcher/statping-ng:v0.90.78"
    url: "{{ urls.statping }}"

  pre_tasks:
    - name: Get list of services
      ansible.builtin.set_fact:
        all_names: "{% if url.monitor is defined %}{{ all_names | default([]) + [item.key|capitalize]}}{% else %}{{ all_names | default([]) }}{% endif %}"
      vars:
        url: "{{ item.value }}"
      loop: "{{ urls | dict2items }}"
    - name: Get list of urls
      ansible.builtin.include_role:
        name: urls
      vars:
        url: "{{ item.value }}"
        accumulate: true
        type: "monitor"
      loop: "{{ urls | dict2items }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
        files: [{}]
    - role: docker
    - role: traefik
      vars:
        servers: [{}]
