---
- name: Install tinystatus
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/tinystatus.yml

  pre_tasks:
    - name: Get list of services
      ansible.builtin.set_fact:
        all_names: "{% if url.monitor is defined %}{{ all_names | default([]) + [item.key | capitalize] }}{% else %}{{ all_names | default([]) }}{% endif %}"
      vars:
        url: "{{ item.value }}"
      loop: "{{ urls | dict2items }}"

    - name: Get list of urls
      ansible.builtin.include_role:
        name: urls
      vars:
        urls_url: "{{ item.value }}"
        urls_accumulate: true
        urls_type: "monitor"
      loop: "{{ urls | dict2items }}"

  roles:
    - role: urls
    - role: packages
    - role: git
    - role: files
    - role: files
      tags: incident
      vars:
        files_copy:
          - src: "incidents.txt"
            destination_path: "{{ working_dir }}"
    - role: nginx
    - role: traefik

  post_tasks:
    - name: Make crontab for tinystatus
      tags: cron
      ansible.builtin.cron:
        name: "Update statuspage"
        minute: "*/2"
        job: "{{ location.scripts }}/tinystatus_cron.sh > /dev/null || \
          {{ location.scripts }}/alert.sh 'ERROR: tinystatus failed!'"
