---
- name: Install tinystatus
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "tinystatus"
    url: "{{ urls.tinystatus }}"

  pre_tasks:
    - name: Get list of services
      ansible.builtin.set_fact:
        all_names: "{% if url.monitor is defined %}{{ all_names | default([]) + [item.key | capitalize] }}{% else %}{{ all_names | default([]) }}{% endif %}"
      vars:
        url: "{{ item.value }}"
      loop: "{{ urls | dict2items }}"
    - name: Get list of urls
      ansible.builtin.include_role:
        name: urls
      vars:
        urls_url: "{{ item.value }}"
        urls_accumulate: true
        urls_type: "monitor"
      loop: "{{ urls | dict2items }}"

    - name: Check for tinystatus repo
      ansible.builtin.stat:
        path: "{{ base_directory }}/{{ service_directory }}/tinystatus"
      register: clone_results

    - name: Install dependencies
      tags: packages
      ansible.builtin.include_role:
        name: packages
      vars:
        packages_native:
          - gnu-netcat

  roles:
    - role: git
      vars:
        git_repo: https://github.com/mstcl/tinystatus.git
        git_destination: "{{ base_directory }}/{{ service_directory }}/tinystatus"
        git_branch: master
      when: not clone_results.stat.exists
    - role: config
      vars:
        config_files:
          - template_name: "checks.csv"
            destination_path: "{{ base_directory }}/{{ service_directory }}/tinystatus"
          - template_name: "tinystatus_cron.sh"
            destination_path: "{{ base_directory }}/scripts"
            permission: "0555"
    - role: config
      tags: incident
      vars:
        config_copies:
          - file_name: "incidents.txt"
            destination_path: "{{ base_directory }}/{{ service_directory }}/tinystatus"

  post_tasks:
    - name: Make crontab for tinystatus
      tags: cron
      ansible.builtin.cron:
        name: "Update statuspage"
        minute: "*/2"
        job: "{{ base_directory }}/scripts/tinystatus_cron.sh > /dev/null || \
          {{ base_directory }}/scripts/alert.sh 'ERROR: tinystatus failed!'"

  handlers:
    - name: Restart compose stack
      ansible.builtin.import_tasks: ../roles/docker/handlers/main.yml
