---
- name: Install traefik-bouncer
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/traefik-bouncer.yml
  vars:
    service_directory: "traefik-bouncer"
    image: "fbonalair/traefik-crowdsec-bouncer:0.5.0"

  pre_tasks:
    - name: Get api-key
      when: bouncer_api_key | length == 0
      block:
        - name: Generate key
          become: true
          changed_when: false
          ansible.builtin.command:
            argv:
              - cscli
              - bouncers
              - add
              - "{{ service_directory }}"
              - "-o"
              - json
          register: generate_results
        - name: Set key
          ansible.builtin.set_fact:
            bouncer_api_key: "{{ (generate_results.stdout | from_json) }}"
        - name: Print API key to save
          ansible.builtin.debug:
            msg:
              [
                "TRAEFIK-BOUNCER API KEY TO SAVE INTO INFISICAL:",
                "{{ bouncer_api_key }}",
              ]

  roles:
    - role: config
    - role: docker
    - role: traefik
      vars:
        traefik_create_service: false
        traefik_create_router: false
        traefik_additional_content: |2
            middlewares:
              crowdsec-bouncer:
                forwardAuth:
                  address: "http://traefik-bouncer:8080/api/v1/forwardAuth"
                  trustForwardHeader: true
