---
- name: Install traefik
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "traefik"
    service_image: "traefik"
    image_tag: "v2.10"
    config_file: "traefik.yml"
    network: "traefik-net"
    cf_email: "{{ lookup('get_secrets', path='/cloudflare', secret_name='CF_EMAIL') }}"
    cf_token: "{{ lookup('get_secrets', path='/cloudflare', secret_name='CF_API_TOKEN_TRAEFIK') }}"
    url: "{{ urls.traefik }}"

  pre_tasks:
    - name: Create docker networks for traefik
      tags: ["docker", "network"]
      block:
        - name: Create docker network for traefik and bouncer
          community.docker.docker_network:
            name: "bouncer"
            ipam_config:
              - subnet: 172.24.0.0/24
        - name: Create docker network for other services
          community.docker.docker_network:
            name: "{{ item }}"
          loop:
            - "{{ docker.traefik_network }}"
            - "{{ docker.expose_network }}"

    - name: Check if logrotate is installed
      tags: packages
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "logrotate test result"
      debug:
        msg: "logrotate not installed. Run setup_remote.yml again"
      when: "'logrotate' not in ansible_facts.packages"

  roles:
    - role: ufw
      vars:
        local: false
        port: 80
    - role: ufw
      vars:
        local: false
        port: 443
    - role: urls
    - role: config
      become: true
      vars:
        directories:
          -
          - path: "{{ base_directory }}/{{ service_directory }}/dynamic"
          - path: "{{ location.docker_data }}/{{ service_directory }}/certs"
            owner: "2000"
          - path: "{{ location.docker_data }}/{{ service_directory }}/plugins/sources"
            owner: "2000"
          - path: "/var/log/traefik"
            owner: "0"
        files: [{}]
        copies:
          - file_name: "middlewares.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/dynamic"
          - file_name: "security.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/dynamic"
    - role: docker
    - role: traefik
      vars:
        create_service: false
        redirect: true
        service_name: "api@internal"
        trailing_slash: false
        router_name: "traefik"
        rule: "(Host(`{{ url.sub + '.' + base_tld }}`) && (PathPrefix(`/{{ url.path }}`) || PathPrefix(`/api`)))"
        middlewares:
          - "internal-ip@file"

  post_tasks:
    - name: Restrict traefik certificates and logs
      become: true
      tags: permission
      block:
        - name: Change mode of certs
          ansible.builtin.shell: "sudo chmod 600 \
                                  {{ location.docker_data }}/{{ service_directory }}/\
                                  certs/acme.json"
        - name: Change mode of logs
          ansible.builtin.shell: "sudo chmod 644 \
                                  /var/log/traefik/*.log"

    - name: Configure log rotate
      tags: log
      ansible.builtin.copy:
        mode: "0644"
        owner: "root"
        dest: "/etc/logrotate.d/traefik"
        force: false
        content: |
          /var/log/traefik/*.log {
            size 10M
            rotate 30
            missingok
            notifempty
            compress
            dateext
            dateformat .%Y-%m-%d
            create 0644 traefik traefik
            postrotate
              docker kill --signal="USR1" {{ service_directory }}
            endscript
          }
      become: true
