---
- name: Install traefik
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/traefik.yml
  vars:
    service_directory: "traefik"
    image: "traefik:2.11"
    url: "{{ urls.traefik }}"

  pre_tasks:
    - name: Check if logrotate is installed
      tags: packages
      ansible.builtin.package_facts:
        manager: "auto"

  roles:
    - role: create_docker_network
      vars:
        create_docker_network_networks:
          - name: "{{ network }}"
            subnet: "{{ ipam_subnet }}.0/24"
          - name: "{{ docker.traefik_network }}"
          - name: "{{ docker.expose_network }}"
    - role: packages
      vars:
        packages_native:
          - logrotate
    - role: systemd
      vars:
        systemd_services:
          - "logrotate.timer"
      when: "'logrotate' not in ansible_facts.packages"
    - role: create_host_users
      vars:
        create_host_users_users:
          - name: "traefik"
            uid: 2000
    - role: ufw
      vars:
        ufw_local: false
        ufw_port: 80
    - role: ufw
      vars:
        ufw_local: false
        ufw_port: 443
    - role: urls
    - role: config
      become: true
      vars:
        config_directories:
          -
          - path: "{{ base_directory }}/{{ service_directory }}/dynamic"
          - path: "{{ location.docker_data }}/{{ service_directory }}/certs"
            owner: "2000"
          - path: "{{ location.docker_data }}/{{ service_directory }}/plugins/sources"
            owner: "2000"
          - path: "/var/log/traefik"
            owner: "0"
        config_files: [{}]
        config_copies:
          - file_name: "middlewares.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/dynamic"
          - file_name: "security.yml"
            destination_path: "{{ base_directory }}/{{ service_directory }}/dynamic"
    - role: docker
    - role: traefik
      vars:
        traefik_create_service: false
        traefik_redirect: true
        traefik_service_name: "api@internal"
        traefik_trailing_slash: false
        traefik_router_name: "traefik"
        traefik_rule: "(Host(`{{ url.sub + '.' + base_tld }}`) && (PathPrefix(`/{{ url.path }}`) || PathPrefix(`/api`)))"
        traefik_middlewares:
          - "internal-ip@file"

  post_tasks:
    - name: Restrict traefik certificates and logs
      become: true
      tags: permission
      block:
        - name: Change mode of certs
          changed_when: false
          ansible.builtin.command: "sudo chmod 600 \
                                  {{ location.docker_data }}/{{ service_directory }}/\
                                  certs/acme.json"
        - name: Change mode of logs
          changed_when: false
          ansible.builtin.command: "sudo chmod 644 \
                                  /var/log/traefik/*.log"

    - name: Configure log rotate
      tags: log
      ansible.builtin.copy:
        mode: "0644"
        owner: "root"
        dest: "/etc/logrotate.d/traefik"
        force: false
        content: |
          /var/log/traefik/*.log {
            size 10M
            rotate 30
            missingok
            notifempty
            compress
            dateext
            dateformat .%Y-%m-%d
            create 0644 traefik traefik
            postrotate
              docker kill --signal="USR1" {{ service_directory }}
            endscript
          }
      become: true
