---
- name: Install unbound
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "unbound"
    service_image: "mvance/unbound"
    image_tag: "latest"
    network: "dns-net"
    config_file: "unbound.conf"

  pre_tasks:
    - name: Create docker network for adguard and unbound
      tags: ["docker", "network"]
      community.docker.docker_network:
        name: "{{ network }}"
        ipam_config:
          - subnet: 172.27.0.0/24

  roles:
    - role: config
      vars:
        directories:
          - path: "{{ base_directory }}/{{ service_directory }}/config"
        copies:
          - destination_path: "{{ base_directory }}/{{ service_directory }}/config"
    - role: docker
      vars:
        run: false

  post_tasks:
    - name: Fetch root hints
      tags: update
      ansible.builtin.uri:
        url: "https://www.internic.net/domain/named.cache"
        method: GET
        dest: "{{ base_directory }}/{{ service_directory }}/config/root.hints"
      register: result

    - name: Start compose file
      tags: ["docker", "deploy"]
      ansible.builtin.include_tasks: roles/docker/tasks/down_and_up.yml
      vars:
        force_up: true
