---
- name: Install unbound
  hosts: homelab:&proxy
  gather_facts: false
  vars_files:
    - vars/unbound.yml

  roles:
    - role: create_docker_network
    - role: files
    - role: fetch_root_hints
    - role: docker
