---
- name: Install vaultwarden
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/vaultwarden.yml

  roles:
    - role: urls
    - role: files
    - role: docker
    - role: traefik
    - role: backup
