---
- name: Install vaultwarden
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "vaultwarden"
    service_image: "vaultwarden/server"
    image_tag: "1.30.3"
    url: "{{ urls.vaultwarden }}"
    # SECRETS
    smtp_host: "{{ lookup('get_secrets', path='/smtp', secret_name='SMTP_HOST') }}"
    smtp_user: "{{ lookup('get_secrets', path='/smtp', secret_name='SMTP_USER') }}"
    smtp_password: "{{ lookup('get_secrets', path='/smtp', secret_name='SMTP_PASSWORD') }}"
    smtp_sender: "{{ lookup('get_secrets', path='/vaultwarden', secret_name='VAULTWARDEN_SMTP_SENDER') }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        middlewares:
         - "internal-ip@file"
