---
- name: Install vaultwarden
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/vaultwarden.yml
  vars:
    service_directory: "vaultwarden"
    image: "vaultwarden/server:1.30.3-alpine"
    url: "{{ urls.vaultwarden }}"

  roles:
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
    - role: traefik
      vars:
        servers:
          - port: 80
        middlewares:
          - "internal-ip@file"
    - role: backup
