---
- name: Install watchyourlan
  hosts: homelab
  gather_facts: false
  vars:
    service_directory: "watchyourlan"
    image: "aceberg/watchyourlan:1.0.6"
    url: "{{ urls.watchyourlan }}"

  roles:
    - role: ufw
      vars:
        port: 8840
    - role: urls
    - role: config
      vars:
        directories: [{}]
    - role: docker
      vars:
        bot_token: "{{ lookup('get_secrets', path='/telegram', secret_name='LAN_BOT_TOKEN') }}"
        chat_id: "{{ lookup('get_secrets', path='/telegram', secret_name='CHAT_ID')  }}"
    - role: traefik
      vars:
        servers:
          - port: 8840
            url: "{{ base_lanip }}"
        middlewares:
          - "authelia@file"
          - "internal-ip@file"
