---
- name: Install watchyourlan
  hosts: homelab
  gather_facts: false
  vars_files:
    - vars/watchyourlan.yml
  vars:
    service_directory: "watchyourlan"
    image: "aceberg/watchyourlan:1.0.6"
    url: "{{ urls.watchyourlan }}"

  roles:
    - role: ufw
      vars:
        ufw_port: 8840
    - role: urls
    - role: config
      vars:
        config_directories: [{}]
    - role: docker
    - role: traefik
      vars:
        traefik_servers:
          - port: 8840
            url: "{{ base_lanip }}"
        traefik_middlewares:
          - "authelia@file"
          - "internal-ip@file"
