---
- name: Install whatsapp-bridge
  hosts: homelab
  gather_facts: false
  vars_files:
    - "vars/whatsapp-bridge.yml"
  vars:
    service_directory: "whatsapp-bridge"
    image: "dock.mau.dev/mautrix/whatsapp:v0.10.5"

  pre_tasks:
    - name: Check if wa.yaml registration config already exists
      ansible.builtin.stat:
        path: "{{ appservice_registration.destination }}"
        get_checksum: false
        get_mime: false
        get_attributes: false
      register: stat_registration

  roles:
    - role: config
      vars:
        config_directories:
          - path: "{{ config_location }}"
            owner: "1000"
            permission: "0755"
          - path: "{{ location.docker_data }}/{{ service_directory }}"
            owner: "1000"
            permission: "0755"
          - path: "{{ postgres.location }}"
            owner: "70"
            permission: "0700"
    - role: config
      vars:
        config_files:
          - destination_path: "{{ config_location }}"
          - file_name: "registration.yaml"
            destination_path: "{{ appservice_registration.destination }}"
            when: not stat_registration.stat.exists
    - role: docker
      vars:
        docker_attach_postgres: true
    - role: traefik
      vars:
        traefik_servers:
          - port: 8008
