---
- name: Copy existing files over
  tags: files
  ansible.builtin.copy:
    src: "{{ hostvars.localhost.base_directory }}/files/\
          {{ service_directory }}/files/\
          {{ item.src }}"
    dest: "{{ item.destination_path | default(base_directory + '/' + service_directory) }}\
           /{{ item.src }}"
    mode: "{{ item.permission | default('0644') }}"
    owner: "{{ item.owner | default('1000') }}"
  with_items: "{{ files_copy }}"
