---
- name: Ensure files/directories exists (touch/mkdir)
  tags: files
  ansible.builtin.include_tasks: make.yml
  when: files_make is defined

- name: Template files
  tags: ["files", "template"]
  ansible.builtin.include_tasks: template.yml
  when: files_template is defined

- name: Copy existing files over
  tags: files
  ansible.builtin.include_tasks: copy.yml
  when: files_copy is defined
